In [106]:
import pandas as pd
import numpy as np
import sqlite3
from sqlalchemy import create_engine
engine = create_engine('sqlite:///hist_trips.sqlite', echo=False)

In [107]:
# Store filepath in a variable
file_one = "data/Hist_Divvy_Trips_2018_Q4.csv"
file_two = "data/Hist_Divvy_Trips_2019_Q1.csv"
file_three = "data/Hist_Divvy_Trips_2019_Q2.csv"
file_four = "data/Hist_Divvy_Trips_2019_Q3.csv"
station = "data/Divvy_Bicycle_Stations.csv"

In [108]:
file_one_df = pd.read_csv(file_one, encoding="ISO-8859-1")
file_two_df = pd.read_csv(file_two, encoding="ISO-8859-1")
file_three_df = pd.read_csv(file_three, encoding="ISO-8859-1")
file_four_df = pd.read_csv(file_four, encoding="ISO-8859-1")
stations_df = pd.read_csv(station, encoding="ISO-8859-1")

In [109]:
vertical_stack_df = pd.concat([file_one_df, file_two_df], axis=0)

In [110]:
vertcl_stck_df = pd.concat([vertical_stack_df, file_three_df], axis=0)

In [111]:
hist_divvy_df = pd.concat([vertcl_stck_df, file_four_df], axis=0)

In [112]:
hist_divvy_df.count()

trip_id              3104905
start_time           3104905
end_time             3104905
bikeid               3104905
tripduration         3104905
from_station_id      3104905
from_station_name    3104905
to_station_id        3104905
to_station_name      3104905
usertype             3104905
gender               2672288
birthyear            2686341
dtype: int64

In [113]:
hist_divvy_df

,trip_id,start_time,end_time,bikeid,tripduration,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear
0,20983539,10/1/2018,10/1/2018,3083,682,125,Rush St & Hubbard St,175,Wells St & Polk St,Customer,NaN,NaN
1,20983543,10/1/2018,10/1/2018,4249,"1,002.00",47,State St & Kinzie St,176,Clark St & Elm St,Customer,NaN,NaN
2,20983548,10/1/2018,10/1/2018,2062,"1,072.00",121,Blackstone Ave & Hyde Park Blvd,121,Blackstone Ave & Hyde Park Blvd,Customer,Male,1905-06-19
3,20983551,10/1/2018,10/1/2018,4039,"2,074.00",620,Orleans St & Chestnut St (NEXT Apts),511,Albany Ave & Bloomingdale Ave,Customer,NaN,NaN
4,20983556,10/1/2018,10/1/2018,1686,534,98,LaSalle St & Washington St,321,Wabash Ave & 9th St,Customer,Male,1905-06-17
5,20983560,10/1/2018,10/1/2018,5140,404,50,Clark St & Congress Pkwy,50,Clark St & Congress Pkwy,Customer,NaN,NaN
6,20983569,10/1/2018,10/1/2018,3616,"1,374.00",35,Streeter Dr & Grand Ave,301,Clark St & Schiller St,Customer,NaN,NaN
7,20983578,10/1/2018,10/1/2018,5569,859,299,Halsted St & Roscoe St,234,Clark St & Montrose Ave,Customer,NaN,NaN
8,20983592,10/1/2018,10/1/2018,3732,487,515,Paulina St & Howard St,597,Chicago Ave & Washington St,Customer,Male,1905-06-08
9,20983595,10/1/2018,10/1/2018,2018,"13,613.00",57,Clinton St & Roosevelt Rd,54,Ogden Ave & Chicago Ave,Customer,NaN,NaN
10,20983674,10/1/2018,10/1/2018,3133,940,240,Sheridan Rd & Irving Park Rd,220,Clark St & Drummond Pl,Customer,NaN,NaN
11,20983698,10/1/2018,10/1/2018,1162,233,165,Clark St & Grace St,304,Broadway & Waveland Ave,Customer,Female,1905-06-01
12,20983702,10/1/2018,10/1/2018,3926,717,237,MLK Jr Dr & 29th St,59,Wabash Ave & Roosevelt Rd,Customer,NaN,NaN
13,20983781,10/1/2018,10/1/2018,6066,"1,528.00",458,Broadway & Thorndale Ave,254,Pine Grove Ave & Irving Park Rd,Customer,Male,1905-05-29
14,20983821,10/1/2018,10/1/2018,1168,873,292,Southport Ave & Clark St,166,Ashland Ave & Wrightwood Ave,Customer,NaN,NaN
15,20983874,10/1/2018,10/1/2018,1029,318,56,Desplaines St & Kinzie St,100,Orleans St & Merchandise Mart Plaza,Customer,Male,1905-06-13
16,20983887,10/1/2018,10/1/2018,1406,"1,304.00",301,Clark St & Schiller St,77,Clinton St & Madison St,Customer,NaN,NaN
17,20983909,10/1/2018,10/1/2018,1418,973,288,Larrabee St & Armitage Ave,47,State St & Kinzie St,Customer,NaN,NaN
18,20983984,10/1/2018,10/1/2018,2918,176,278,Wallace St & 35th St,405,Wentworth Ave & 35th St,Customer,NaN,NaN
19,20984002,10/1/2018,10/1/2018,2870,481,192,Canal St & Adams St,44,State St & Randolph St,Customer,NaN,NaN
20,20984012,10/1/2018,10/1/2018,4720,"16,837.00",54,Ogden Ave & Chicago Ave,44,State St & Randolph St,Customer,NaN,NaN
21,20984048,10/1/2018,10/1/2018,3423,738,44,State St & Randolph St,88,Racine Ave & Randolph St,Customer,Male,1905-06-17
22,20984070,10/1/2018,10/1/2018,3700,576,29,Noble St & Milwaukee Ave,198,Green St & Madison St,Customer,Female,1905-06-17
23,20984191,10/1/2018,10/1/2018,2364,886,50,Clark St & Congress Pkwy,62,McCormick Place,Customer,NaN,NaN
24,20984193,10/1/2018,10/1/2018,3821,843,176,Clark St & Elm St,174,Canal St & Madison St,Customer,NaN,NaN
25,20984201,10/1/2018,10/1/2018,3923,434,417,Cornell Ave & Hyde Park Blvd,420,Ellis Ave & 55th St,Customer,NaN,NaN
26,20984214,10/1/2018,10/1/2018,5748,375,247,Shore Dr & 55th St,322,Kimbark Ave & 53rd St,Customer,NaN,NaN
27,20984268,10/1/2018,10/1/2018,4104,484,74,Kingsbury St & Erie St,191,Canal St & Monroe St (*),Customer,Male,1905-06-16
28,20984280,10/1/2018,10/1/2018,4201,562,405,Wentworth Ave & 35th St,548,Morgan St & Pershing Rd,Customer,Male,1905-06-09
29,20984306,10/1/2018,10/1/2018,1686,538,321,Wabash Ave & 9th St,287,Franklin St & Monroe St,Customer,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1048545,24607272,8/26/2019,8/26/2019,4228,186,260,Kedzie Ave & Milwaukee Ave,501,Richmond St & Diversey Ave,Subscriber,Male,1905-06-11
1048546,24607273,8/26/2019,8/26/2019,4999,502,74,Kingsbury St & Erie St,77,Clinton St & Madison St,Subscriber,Male,1905-06-01
1048547,24607274,8/26/2019,8/26/2019,2750,665,174,Canal St & Madison St,140,Dearborn Pkwy & Delaware Pl,Subscriber,Male,1905-06-12
1048548,24607276,8/26/2019,8/26/2019,2841,318,312,Clarendon Ave & Gordon Ter,232,Pine Grove Ave & Waveland Ave,Subscriber,Male,1905-06-14
1048549,24607277,8/26/2019,8/26/2019,4070,"1,569.00",199,Wabash Ave & Grand Ave,211,St. Clair St & Erie St,Subscriber,Female,1905-06-01
1048550,24607278,8/26/2019,8/26/2019,5641,"1,881.00",107,Desplaines St & Jackson Blvd,299,Halsted St & Roscoe St,Subscriber,Male,1905-06-03
1048551,24607279,8/26/2019,8/26/2019,47,598,114,Sheffield Ave & Waveland Ave,234,Clark St & Montrose Ave,Subscriber,Male,1905-05-19
1048552,24607280,8/26/2019,8/26/2019,978,677,285,Wood St & Hubbard St,305,Western Ave & Division St,Subscriber,Female,1905-06-18
1048553,24607282,8/26/2019,8/26/2019,3330,523,90,Millennium Park,168,Michigan Ave & 14th St,Subscriber,Male,1905-06-03
1048554,24607283,8/26/2019,8/26/2019,4593,466,116,Western Ave & Winnebago Ave,511,Albany Ave & Bloomingdale Ave,Subscriber,Female,1905-06-12
1048555,24607285,8/26/2019,8/26/2019,1799,"1,430.00",287,Franklin St & Monroe St,313,Lakeview Ave & Fullerton Pkwy,Subscriber,Female,1905-06-17
1048556,24607286,8/26/2019,8/26/2019,5222,275,29,Noble St & Milwaukee Ave,350,Ashland Ave & Chicago Ave,Subscriber,Male,1905-06-12
1048557,24607287,8/26/2019,8/26/2019,802,845,91,Clinton St & Washington Blvd,182,Wells St & Elm St,Subscriber,Male,1905-06-16
1048558,24607288,8/26/2019,8/26/2019,3888,357,53,Wells St & Huron St,56,Desplaines St & Kinzie St,Subscriber,Female,1905-05-25
1048559,24607289,8/26/2019,8/26/2019,5909,617,287,Franklin St & Monroe St,627,LaSalle Dr & Huron St,Subscriber,Male,1905-06-17
1048560,24607290,8/26/2019,8/26/2019,1563,"1,135.00",279,Halsted St & 35th St,237,MLK Jr Dr & 29th St,Subscriber,Female,1905-06-16
1048561,24607291,8/26/2019,8/26/2019,1083,709,81,Daley Center Plaza,48,Larrabee St & Kingsbury St,Subscriber,Female,1905-06-16
1048562,24607292,8/26/2019,8/26/2019,5016,"2,148.00",196,Cityfront Plaza Dr & Pioneer Ct,325,Clark St & Winnemac Ave,Subscriber,Female,1905-06-09
1048563,24607295,8/26/2019,8/26/2019,1236,263,37,Dearborn St & Adams St,89,Financial Pl & Ida B Wells Dr,Subscriber,Female,1905-06-11
1048564,24607298,8/26/2019,8/26/2019,2708,"2,407.00",283,LaSalle St & Jackson Blvd,316,Damen Ave & Sunnyside Ave,Subscriber,Male,1905-06-10
1048565,24607300,8/26/2019,8/26/2019,2387,263,156,Clark St & Wellington Ave,220,Clark St & Drummond Pl,Subscriber,Male,1905-06-13
1048566,24607302,8/26/2019,8/26/2019,5466,551,251,Clarendon Ave & Leland Ave,240,Sheridan Rd & Irving Park Rd,Subscriber,Female,1905-05-21
1048567,24607303,8/26/2019,8/26/2019,5097,479,43,Michigan Ave & Washington St,77,Clinton St & Madison St,Subscriber,Male,1905-05-22
1048568,24607304,8/26/2019,8/26/2019,6005,408,300,Broadway & Barry Ave,143,Sedgwick St & Webster Ave,Subscriber,Male,1905-06-16
1048569,24607305,8/26/2019,8/26/2019,4,"1,697.00",313,Lakeview Ave & Fullerton Pkwy,313,Lakeview Ave & Fullerton Pkwy,Subscriber,Male,1905-06-09
1048570,24607306,8/26/2019,8/26/2019,300,329,286,Franklin St & Adams St (Temp),175,Wells St & Polk St,Subscriber,Male,1905-05-30
1048571,24607308,8/26/2019,8/26/2019,6443,"1,983.00",68,Clinton St & Tilden St,177,Theater on the Lake,Subscriber,Male,1905-05-29
1048572,24607309,8/26/2019,8/26/2019,3558,"1,359.00",52,Michigan Ave & Lake St,282,Halsted St & Maxwell St,Subscriber,Male,1905-06-11
1048573,24607310,8/26/2019,8/26/2019,5055,622,283,LaSalle St & Jackson Blvd,125,Rush St & Hubbard St,Subscriber,Male,1905-05-31
1048574,24607311,8/26/2019,8/26/2019,2122,906,91,Clinton St & Washington Blvd,48,Larrabee St & Kingsbury St,Subscriber,Male,1905-06-11

In [114]:
hist_divy_df = hist_divvy_df.dropna()

In [115]:
len(hist_divy_df)

2672285

In [116]:
hist_dvy_df = hist_divy_df.drop(["bikeid", "from_station_name", "to_station_name"], axis=1)

In [117]:
len(hist_dvy_df)

2672285

In [118]:
hist_dvy_df

,trip_id,start_time,end_time,tripduration,from_station_id,to_station_id,usertype,gender,birthyear
2,20983548,10/1/2018,10/1/2018,"1,072.00",121,121,Customer,Male,1905-06-19
4,20983556,10/1/2018,10/1/2018,534,98,321,Customer,Male,1905-06-17
8,20983592,10/1/2018,10/1/2018,487,515,597,Customer,Male,1905-06-08
11,20983698,10/1/2018,10/1/2018,233,165,304,Customer,Female,1905-06-01
13,20983781,10/1/2018,10/1/2018,"1,528.00",458,254,Customer,Male,1905-05-29
15,20983874,10/1/2018,10/1/2018,318,56,100,Customer,Male,1905-06-13
21,20984048,10/1/2018,10/1/2018,738,44,88,Customer,Male,1905-06-17
22,20984070,10/1/2018,10/1/2018,576,29,198,Customer,Female,1905-06-17
27,20984268,10/1/2018,10/1/2018,484,74,191,Customer,Male,1905-06-16
28,20984280,10/1/2018,10/1/2018,562,405,548,Customer,Male,1905-06-09
30,20984348,10/1/2018,10/1/2018,603,44,48,Customer,Male,1905-06-16
31,20984367,10/1/2018,10/1/2018,305,304,165,Customer,Female,1905-06-01
32,20984395,10/1/2018,10/1/2018,824,40,273,Customer,Male,1905-06-03
34,20984443,10/1/2018,10/1/2018,948,299,20,Customer,Male,1905-06-06
35,20984485,10/1/2018,10/1/2018,267,80,91,Customer,Female,1905-06-14
37,20984598,10/1/2018,10/1/2018,409,175,33,Customer,Male,1905-06-16
38,20984600,10/1/2018,10/1/2018,698,124,202,Customer,Female,1905-06-15
40,20984704,10/1/2018,10/1/2018,"1,183.00",61,287,Customer,Male,1905-06-16
41,20984769,10/1/2018,10/1/2018,"1,772.00",165,35,Customer,Male,1905-05-29
44,20984950,10/1/2018,10/1/2018,"1,497.00",290,86,Customer,Female,1905-06-16
47,20985108,10/1/2018,10/1/2018,"1,831.00",347,35,Customer,Male,1905-05-20
48,20985109,10/1/2018,10/1/2018,699,7,192,Customer,Male,1905-06-17
50,20985162,10/1/2018,10/1/2018,446,59,49,Customer,Male,1905-06-13
53,20985224,10/1/2018,10/1/2018,376,623,43,Customer,Male,1905-06-11
57,20985399,10/1/2018,10/1/2018,703,190,156,Customer,Female,1905-06-16
58,20985527,10/1/2018,10/1/2018,666,107,48,Customer,Male,1905-06-03
59,20985554,10/1/2018,10/1/2018,765,94,20,Customer,Male,1905-06-07
60,20985629,10/1/2018,10/1/2018,"1,287.00",67,134,Customer,Male,1905-06-20
61,20985674,10/1/2018,10/1/2018,"1,256.00",659,71,Customer,Male,1905-06-04
62,20985701,10/1/2018,10/1/2018,"1,890.00",460,605,Customer,Male,1905-06-02
...,...,...,...,...,...,...,...,...,...
1048545,24607272,8/26/2019,8/26/2019,186,260,501,Subscriber,Male,1905-06-11
1048546,24607273,8/26/2019,8/26/2019,502,74,77,Subscriber,Male,1905-06-01
1048547,24607274,8/26/2019,8/26/2019,665,174,140,Subscriber,Male,1905-06-12
1048548,24607276,8/26/2019,8/26/2019,318,312,232,Subscriber,Male,1905-06-14
1048549,24607277,8/26/2019,8/26/2019,"1,569.00",199,211,Subscriber,Female,1905-06-01
1048550,24607278,8/26/2019,8/26/2019,"1,881.00",107,299,Subscriber,Male,1905-06-03
1048551,24607279,8/26/2019,8/26/2019,598,114,234,Subscriber,Male,1905-05-19
1048552,24607280,8/26/2019,8/26/2019,677,285,305,Subscriber,Female,1905-06-18
1048553,24607282,8/26/2019,8/26/2019,523,90,168,Subscriber,Male,1905-06-03
1048554,24607283,8/26/2019,8/26/2019,466,116,511,Subscriber,Female,1905-06-12
1048555,24607285,8/26/2019,8/26/2019,"1,430.00",287,313,Subscriber,Female,1905-06-17
1048556,24607286,8/26/2019,8/26/2019,275,29,350,Subscriber,Male,1905-06-12
1048557,24607287,8/26/2019,8/26/2019,845,91,182,Subscriber,Male,1905-06-16
1048558,24607288,8/26/2019,8/26/2019,357,53,56,Subscriber,Female,1905-05-25
1048559,24607289,8/26/2019,8/26/2019,617,287,627,Subscriber,Male,1905-06-17
1048560,24607290,8/26/2019,8/26/2019,"1,135.00",279,237,Subscriber,Female,1905-06-16
1048561,24607291,8/26/2019,8/26/2019,709,81,48,Subscriber,Female,1905-06-16
1048562,24607292,8/26/2019,8/26/2019,"2,148.00",196,325,Subscriber,Female,1905-06-09
1048563,24607295,8/26/2019,8/26/2019,263,37,89,Subscriber,Female,1905-06-11
1048564,24607298,8/26/2019,8/26/2019,"2,407.00",283,316,Subscriber,Male,1905-06-10
1048565,24607300,8/26/2019,8/26/2019,263,156,220,Subscriber,Male,1905-06-13
1048566,24607302,8/26/2019,8/26/2019,551,251,240,Subscriber,Female,1905-05-21
1048567,24607303,8/26/2019,8/26/2019,479,43,77,Subscriber,Male,1905-05-22
1048568,24607304,8/26/2019,8/26/2019,408,300,143,Subscriber,Male,1905-06-16
1048569,24607305,8/26/2019,8/26/2019,"1,697.00",313,313,Subscriber,Male,1905-06-09
1048570,24607306,8/26/2019,8/26/2019,329,286,175,Subscriber,Male,1905-05-30
1048571,24607308,8/26/2019,8/26/2019,"1,983.00",68,177,Subscriber,Male,1905-05-29
1048572,24607309,8/26/2019,8/26/2019,"1,359.00",52,282,Subscriber,Male,1905-06-11
1048573,24607310,8/26/2019,8/26/2019,622,283,125,Subscriber,Male,1905-05-31
1048574,24607311,8/26/2019,8/26/2019,906,91,48,Subscriber,Male,1905-06-11

In [119]:
hist_dvy_df.index = range(len(hist_dvy_df.index))

In [120]:
hst_dvy_df = hist_dvy_df[hist_dvy_df.usertype == "Subscriber"]

In [121]:
hst_dvy_df.head()

,trip_id,start_time,end_time,tripduration,from_station_id,to_station_id,usertype,gender,birthyear
17075,20983530,10/1/2018,10/1/2018,"1,698.00",85,166,Subscriber,Male,1905-06-14
17076,20983531,10/1/2018,10/1/2018,416,13,144,Subscriber,Female,1905-06-04
17077,20983532,10/1/2018,10/1/2018,534,59,197,Subscriber,Male,1905-06-08
17078,20983533,10/1/2018,10/1/2018,778,328,419,Subscriber,Female,1905-05-13
17079,20983534,10/1/2018,10/1/2018,"1,102.00",93,159,Subscriber,Female,1905-06-15

In [123]:
hst_dvy_df.to_sql('hist_trips', con=engine)

In [124]:
stations_df.to_sql('stations', con=engine)

In [125]:

engine.execute("SELECT * FROM hist_trips").fetchall()

[(17075, 20983530, '10/1/2018', '10/1/2018', '1,698.00', 85, 166, 'Subscriber', 'Male', '1905-06-14'),
 (17076, 20983531, '10/1/2018', '10/1/2018', '416', 13, 144, 'Subscriber', 'Female', '1905-06-04'),
 (17077, 20983532, '10/1/2018', '10/1/2018', '534', 59, 197, 'Subscriber', 'Male', '1905-06-08'),
 (17078, 20983533, '10/1/2018', '10/1/2018', '778', 328, 419, 'Subscriber', 'Female', '1905-05-13'),
 (17079, 20983534, '10/1/2018', '10/1/2018', '1,102.00', 93, 159, 'Subscriber', 'Female', '1905-06-15'),
 (17080, 20983535, '10/1/2018', '10/1/2018', '229', 229, 318, 'Subscriber', 'Male', '1905-06-14'),
 (17081, 20983536, '10/1/2018', '10/1/2018', '3,039.00', 148, 11, 'Subscriber', 'Male', '1905-06-19'),
 (17082, 20983537, '10/1/2018', '10/1/2018', '354', 374, 130, 'Subscriber', 'Male', '1905-06-14'),
 (17083, 20983538, '10/1/2018', '10/1/2018', '174', 268, 289, 'Subscriber', 'Male', '1905-06-06'),
 (17084, 20983540, '10/1/2018', '10/1/2018', '577', 110, 289, 'Subscriber', 'Male', '1905-06-04'),
 (17085, 20983541, '10/1/2018', '10/1/2018', '1,225.00', 47, 176, 'Subscriber', 'Female', '1905-05-13'),
 (17086, 20983542, '10/1/2018', '10/1/2018', '910', 319, 256, 'Subscriber', 'Male', '1905-06-11'),
 (17087, 20983544, '10/1/2018', '10/1/2018', '411', 68, 91, 'Subscriber', 'Male', '1905-05-17'),
 (17088, 20983545, '10/1/2018', '10/1/2018', '150', 289, 268, 'Subscriber', 'Male', '1905-06-06'),
 (17089, 20983546, '10/1/2018', '10/1/2018', '204', 53, 74, 'Subscriber', 'Male', '1905-05-29'),
 (17090, 20983547, '10/1/2018', '10/1/2018', '187', 427, 430, 'Subscriber', 'Male', '1905-06-09'),
 (17091, 20983549, '10/1/2018', '10/1/2018', '250', 241, 320, 'Subscriber', 'Male', '1905-06-15'),
 (17092, 20983550, '10/1/2018', '10/1/2018', '2,073.00', 620, 511, 'Subscriber', 'Male', '1905-06-13'),
 (17093, 20983552, '10/1/2018', '10/1/2018', '342', 294, 460, 'Subscriber', 'Male', '1905-06-05'),
 (17094, 20983553, '10/1/2018', '10/1/2018', '635', 241, 19, 'Subscriber', 'Male', '1905-06-14'),
 (17095, 20983554, '10/1/2018', '10/1/2018', '1,949.00', 43, 378, 'Subscriber', 'Female', '1905-06-06'),
 (17096, 20983555, '10/1/2018', '10/1/2018', '2,389.00', 627, 49, 'Subscriber', 'Male', '1905-06-14'),
 (17097, 20983557, '10/1/2018', '10/1/2018', '178', 198, 77, 'Subscriber', 'Male', '1905-06-16'),
 (17098, 20983558, '10/1/2018', '10/1/2018', '711', 165, 293, 'Subscriber', 'Male', '1905-05-23'),
 (17099, 20983559, '10/1/2018', '10/1/2018', '296', 173, 35, 'Subscriber', 'Male', '1905-06-16'),
 (17100, 20983561, '10/1/2018', '10/1/2018', '137', 22, 19, 'Subscriber', 'Male', '1905-06-15'),
 (17101, 20983562, '10/1/2018', '10/1/2018', '530', 108, 626, 'Subscriber', 'Male', '1905-06-19'),
 (17102, 20983563, '10/1/2018', '10/1/2018', '511', 108, 626, 'Subscriber', 'Male', '1905-06-21'),
 (17103, 20983564, '10/1/2018', '10/1/2018', '125', 73, 107, 'Subscriber', 'Male', '1905-06-13'),
 (17104, 20983565, '10/1/2018', '10/1/2018', '492', 166, 67, 'Subscriber', 'Male', '1905-06-17'),
 (17105, 20983566, '10/1/2018', '10/1/2018', '370', 293, 295, 'Subscriber', 'Male', '1905-05-23'),
 (17106, 20983567, '10/1/2018', '10/1/2018', '204', 291, 289, 'Subscriber', 'Female', '1905-06-15'),
 (17107, 20983568, '10/1/2018', '10/1/2018', '160', 148, 184, 'Subscriber', 'Male', '1905-06-17'),
 (17108, 20983570, '10/1/2018', '10/1/2018', '135', 107, 73, 'Subscriber', 'Male', '1905-06-13'),
 (17109, 20983571, '10/1/2018', '10/1/2018', '538', 511, 158, 'Subscriber', 'Male', '1905-06-13'),
 (17110, 20983572, '10/1/2018', '10/1/2018', '371', 181, 624, 'Subscriber', 'Male', '1905-06-12'),
 (17111, 20983573, '10/1/2018', '10/1/2018', '1,076.00', 302, 298, 'Subscriber', 'Female', '1905-05-12'),
 (17112, 20983574, '10/1/2018', '10/1/2018', '987', 49, 286, 'Subscriber', 'Male', '1905-06-14'),
 (17113, 20983575, '10/1/2018', '10/1/2018', '424', 329, 157, 'Subscriber', 'Female', '1905-06-03'),
 (17114, 20983576, '10/1/2018', '10/1/2018', '1,896.00', 75, 406, 'Subscriber', 'Male', '1905-05-19'),
 (17115, 20983577, '10/1/2018', '10/1/2018', '485', 120, 401, 'Subscriber', 'Male', '1905-05-29'),
 (17116, 20983579, '10/1/2018', '10/1/2018', '252', 284, 52, 'Subscriber', 'Male', '1905-06-08'),
 (17117, 20983580, '10/1/2018', '10/1/2018', '296', 35, 173, 'Subscriber', 'Male', '1905-06-16'),
 (17118, 20983581, '10/1/2018', '10/1/2018', '110', 73, 107, 'Subscriber', 'Male', '1905-06-10'),
 (17119, 20983582, '10/1/2018', '10/1/2018', '89', 107, 73, 'Subscriber', 'Male', '1905-06-10'),
 (17120, 20983583, '10/1/2018', '10/1/2018', '1,641.00', 197, 123, 'Subscriber', 'Male', '1905-05-24'),
 (17121, 20983584, '10/1/2018', '10/1/2018', '290', 300, 303, 'Subscriber', 'Female', '1905-06-03'),
 (17122, 20983585, '10/1/2018', '10/1/2018', '489', 260, 123, 'Subscriber', 'Male', '1905-06-06'),
 (17123, 20983586, '10/1/2018', '10/1/2018', '297', 59, 623, 'Subscriber', 'Male', '1905-05-11'),
 (17124, 20983587, '10/1/2018', '10/1/2018', '241', 623, 284, 'Subscriber', 'Male', '1905-05-11'),
 (17125, 20983588, '10/1/2018', '10/1/2018', '1,570.00', 286, 286, 'Subscriber', 'Male', '1905-06-14'),
 (17126, 20983589, '10/1/2018', '10/1/2018', '1,034.00', 625, 523, 'Subscriber', 'Female', '1905-05-20'),
 (17127, 20983590, '10/1/2018', '10/1/2018', '653', 284, 36, 'Subscriber', 'Male', '1905-05-11'),
 (17128, 20983591, '10/1/2018', '10/1/2018', '581', 211, 176, 'Subscriber', 'Male', '1905-06-02'),
 (17129, 20983593, '10/1/2018', '10/1/2018', '80', 22, 19, 'Subscriber', 'Male', '1905-06-20'),
 (17130, 20983594, '10/1/2018', '10/1/2018', '1,226.00', 301, 283, 'Subscriber', 'Male', '1905-05-23'),
 (17131, 20983596, '10/1/2018', '10/1/2018', '144', 118, 118, 'Subscriber', 'Female', '1905-06-13'),
 (17132, 20983597, '10/1/2018', '10/1/2018', '1,312.00', 47, 149, 'Subscriber', 'Male', '1905-06-13'),
 (17133, 20983598, '10/1/2018', '10/1/2018', '3,468.00', 299, 126, 'Subscriber', 'Male', '1905-05-30'),
 (17134, 20983599, '10/1/2018', '10/1/2018', '1,996.00', 493, 24, 'Subscriber', 'Female', '1905-06-01'),
 (17135, 20983600, '10/1/2018', '10/1/2018', '1,000.00', 67, 174, 'Subscriber', 'Male', '1905-06-08'),
 (17136, 20983601, '10/1/2018', '10/1/2018', '380', 198, 81, 'Subscriber', 'Male', '1905-05-21'),
 (17137, 20983602, '10/1/2018', '10/1/2018', '1,302.00', 286, 286, 'Subscriber', 'Male', '1905-06-14'),
 (17138, 20983603, '10/1/2018', '10/1/2018', '817', 299, 251, 'Subscriber', 'Male', '1905-06-14'),
 (17139, 20983604, '10/1/2018', '10/1/2018', '400', 11, 396, 'Subscriber', 'Male', '1905-06-14'),
 (17140, 20983605, '10/1/2018', '10/1/2018', '139', 465, 251, 'Subscriber', 'Male', '1905-06-15'),
 (17141, 20983606, '10/1/2018', '10/1/2018', '288', 340, 324, 'Subscriber', 'Male', '1905-06-14'),
 (17142, 20983607, '10/1/2018', '10/1/2018', '438', 156, 229, 'Subscriber', 'Male', '1905-06-08'),
 (17143, 20983608, '10/1/2018', '10/1/2018', '1,343.00', 60, 315, 'Subscriber', 'Male', '1905-05-17'),
 (17144, 20983609, '10/1/2018', '10/1/2018', '173', 299, 304, 'Subscriber', 'Male', '1905-06-11'),
 (17145, 20983610, '10/1/2018', '10/1/2018', '624', 188, 115, 'Subscriber', 'Female', '1905-06-16'),
 (17146, 20983611, '10/1/2018', '10/1/2018', '436', 21, 317, 'Subscriber', 'Male', '1905-06-16'),
 (17147, 20983612, '10/1/2018', '10/1/2018', '190', 182, 31, 'Subscriber', 'Male', '1905-06-16'),
 (17148, 20983613, '10/1/2018', '10/1/2018', '457', 53, 24, 'Subscriber', 'Male', '1905-06-10'),
 (17149, 20983614, '10/1/2018', '10/1/2018', '360', 21, 36, 'Subscriber', 'Male', '1905-05-21'),
 (17150, 20983615, '10/1/2018', '10/1/2018', '572', 332, 60, 'Subscriber', 'Female', '1905-05-30'),
 (17151, 20983616, '10/1/2018', '10/1/2018', '270', 245, 256, 'Subscriber', 'Female', '1905-06-06'),
 (17152, 20983617, '10/1/2018', '10/1/2018', '193', 264, 38, 'Subscriber', 'Male', '1905-05-07'),
 (17153, 20983618, '10/1/2018', '10/1/2018', '280', 638, 51, 'Subscriber', 'Male', '1905-06-09'),
 (17154, 20983619, '10/1/2018', '10/1/2018', '279', 343, 127, 'Subscriber', 'Male', '1905-06-13'),
 (17155, 20983620, '10/1/2018', '10/1/2018', '1,647.00', 286, 337, 'Subscriber', 'Male', '1905-06-14'),
 (17156, 20983621, '10/1/2018', '10/1/2018', '464', 290, 222, 'Subscriber', 'Male', '1905-05-16'),
 (17157, 20983623, '10/1/2018', '10/1/2018', '212', 182, 289, 'Subscriber', 'Female', '1905-06-12'),
 (17158, 20983624, '10/1/2018', '10/1/2018', '366', 467, 432, 'Subscriber', 'Female', '1905-05-21'),
 (17159, 20983625, '10/1/2018', '10/1/2018', '1,906.00', 499, 499, 'Subscriber', 'Female', '1905-06-12'),
 (17160, 20983626, '10/1/2018', '10/1/2018', '250', 17, 16, 'Subscriber', 'Female', '1905-06-11'),
 (17161, 20983627, '10/1/2018', '10/1/2018', '708', 182, 264, 'Subscriber', 'Male', '1905-06-12'),
 (17162, 20983628, '10/1/2018', '10/1/2018', '1,066.00', 176, 59, 'Subscriber', 'Female', '1905-05-30'),
 (17163, 20983629, '10/1/2018', '10/1/2018', '326', 365, 20, 'Subscriber', 'Female', '1905-06-07'),
 (17164, 20983630, '10/1/2018', '10/1/2018', '220', 53, 48, 'Subscriber', 'Male', '1905-06-13'),
 (17165, 20983631, '10/1/2018', '10/1/2018', '482', 180, 53, 'Subscriber', 'Female', '1905-06-11'),
 (17166, 20983632, '10/1/2018', '10/1/2018', '1,999.00', 315, 315, 'Subscriber', 'Male', '1905-05-17'),
 (17167, 20983633, '10/1/2018', '10/1/2018', '155', 252, 267, 'Subscriber', 'Female', '1905-06-14'),
 (17168, 20983634, '10/1/2018', '10/1/2018', '1,914.00', 500, 38, 'Subscriber', 'Male', '1905-06-15'),
 (17169, 20983635, '10/1/2018', '10/1/2018', '1,063.00', 93, 96, 'Subscriber', 'Female', '1905-06-06'),
 (17170, 20983636, '10/1/2018', '10/1/2018', '108', 48, 364, 'Subscriber', 'Male', '1905-06-06'),
 (17171, 20983637, '10/1/2018', '10/1/2018', '480', 74, 49, 'Subscriber', 'Male', '1905-05-15'),
 (17172, 20983638, '10/1/2018', '10/1/2018', '79', 254, 256, 'Subscriber', 'Male', '1905-06-09'),
 (17173, 20983639, '10/1/2018', '10/1/2018', '256', 299, 300, 'Subscriber', 'Female', '1905-06-18'),
 (17174, 20983640, '10/1/2018', '10/1/2018', '682', 86, 164, 'Subscriber', 'Female', '1905-06-06'),
 (17175, 20983641, '10/1/2018', '10/1/2018', '1,090.00', 478, 493, 'Subscriber', 'Female', '1905-05-19'),
 (17176, 20983642, '10/1/2018', '10/1/2018', '265', 162, 131, 'Subscriber', 'Male', '1905-05-23'),
 (17177, 20983643, '10/1/2018', '10/1/2018', '2,422.00', 337, 110, 'Subscriber', 'Male', '1905-06-14'),
 (17178, 20983644, '10/1/2018', '10/1/2018', '379', 486, 491, 'Subscriber', 'Male', '1905-06-01'),
 (17179, 20983645, '10/1/2018', '10/1/2018', '434', 419, 423, 'Subscriber', 'Male', '1905-06-11'),
 (17180, 20983646, '10/1/2018', '10/1/2018', '925', 16, 133, 'Subscriber', 'Male', '1905-06-17'),
 (17181, 20983647, '10/1/2018', '10/1/2018', '1,274.00', 163, 211, 'Subscriber', 'Male', '1905-06-12'),
 (17182, 20983648, '10/1/2018', '10/1/2018', '253', 340, 13, 'Subscriber', 'Female', '1905-06-13'),
 (17183, 20983649, '10/1/2018', '10/1/2018', '135', 227, 229, 'Subscriber', 'Male', '1905-05-15'),
 (17184, 20983650, '10/1/2018', '10/1/2018', '279', 26, 173, 'Subscriber', 'Female', '1905-06-14'),
 (17185, 20983651, '10/1/2018', '10/1/2018', '491', 172, 133, 'Subscriber', 'Male', '1905-06-13'),
 (17186, 20983652, '10/1/2018', '10/1/2018', '1,071.00', 144, 133, 'Subscriber', 'Female', '1905-06-17'),
 (17187, 20983653, '10/1/2018', '10/1/2018', '538', 46, 91, 'Subscriber', 'Male', '1905-06-14'),
 (17188, 20983654, '10/1/2018', '10/1/2018', '1,187.00', 350, 258, 'Subscriber', 'Female', '1905-06-16'),
 (17189, 20983655, '10/1/2018', '10/1/2018', '584', 75, 55, 'Subscriber', 'Female', '1905-05-15'),
 (17190, 20983656, '10/1/2018', '10/1/2018', '372', 321, 286, 'Subscriber', 'Male', '1905-06-14'),
 (17191, 20983657, '10/1/2018', '10/1/2018', '637', 192, 24, 'Subscriber', 'Male', '1905-06-09'),
 (17192, 20983658, '10/1/2018', '10/1/2018', '383', 620, 211, 'Subscriber', 'Male', '1905-05-16'),
 (17193, 20983659, '10/1/2018', '10/1/2018', '170', 192, 18, 'Subscriber', 'Male', '1905-06-04'),
 (17194, 20983660, '10/1/2018', '10/1/2018', '497', 192, 48, 'Subscriber', 'Male', '1905-05-22'),
 (17195, 20983661, '10/1/2018', '10/1/2018', '291', 175, 75, 'Subscriber', 'Male', '1905-06-03'),
 (17196, 20983662, '10/1/2018', '10/1/2018', '412', 175, 164, 'Subscriber', 'Male', '1905-06-14'),
 (17197, 20983663, '10/1/2018', '10/1/2018', '227', 111, 212, 'Subscriber', 'Male', '1905-06-10'),
 (17198, 20983664, '10/1/2018', '10/1/2018', '1,156.00', 116, 107, 'Subscriber', 'Male', '1905-06-08'),
 (17199, 20983665, '10/1/2018', '10/1/2018', '390', 24, 53, 'Subscriber', 'Male', '1905-06-10'),
 (17200, 20983666, '10/1/2018', '10/1/2018', '764', 192, 7, 'Subscriber', 'Male', '1905-06-04'),
 (17201, 20983667, '10/1/2018', '10/1/2018', '246', 36, 284, 'Subscriber', 'Male', '1905-05-22'),
 (17202, 20983668, '10/1/2018', '10/1/2018', '2,390.00', 506, 283, 'Subscriber', 'Male', '1905-05-15'),
 (17203, 20983669, '10/1/2018', '10/1/2018', '606', 36, 195, 'Subscriber', 'Male', '1905-05-15'),
 (17204, 20983670, '10/1/2018', '10/1/2018', '842', 182, 89, 'Subscriber', 'Female', '1905-06-18'),
 (17205, 20983671, '10/1/2018', '10/1/2018', '437', 324, 94, 'Subscriber', 'Female', '1905-06-12'),
 (17206, 20983672, '10/1/2018', '10/1/2018', '690', 192, 195, 'Subscriber', 'Male', '1905-05-23'),
 (17207, 20983673, '10/1/2018', '10/1/2018', '1,773.00', 180, 317, 'Subscriber', 'Male', '1905-06-03'),
 (17208, 20983675, '10/1/2018', '10/1/2018', '568', 301, 211, 'Subscriber', 'Male', '1905-06-07'),
 (17209, 20983676, '10/1/2018', '10/1/2018', '591', 152, 58, 'Subscriber', 'Female', '1905-05-29'),
 (17210, 20983677, '10/1/2018', '10/1/2018', '690', 627, 75, 'Subscriber', 'Male', '1905-06-04'),
 (17211, 20983678, '10/1/2018', '10/1/2018', '293', 140, 145, 'Subscriber', 'Male', '1905-06-13'),
 (17212, 20983679, '10/1/2018', '10/1/2018', '638', 340, 176, 'Subscriber', 'Male', '1905-06-13'),
 (17213, 20983680, '10/1/2018', '10/1/2018', '1,412.00', 310, 98, 'Subscriber', 'Female', '1905-06-03'),
 (17214, 20983681, '10/1/2018', '10/1/2018', '883', 324, 172, 'Subscriber', 'Female', '1905-06-11'),
 (17215, 20983682, '10/1/2018', '10/1/2018', '556', 259, 69, 'Subscriber', 'Female', '1905-06-13'),
 (17216, 20983683, '10/1/2018', '10/1/2018', '1,201.00', 214, 283, 'Subscriber', 'Female', '1905-05-29'),
 (17217, 20983684, '10/1/2018', '10/1/2018', '271', 7, 43, 'Subscriber', 'Male', '1905-05-23'),
 (17218, 20983685, '10/1/2018', '10/1/2018', '847', 90, 626, 'Subscriber', 'Female', '1905-06-03'),
 (17219, 20983686, '10/1/2018', '10/1/2018', '1,065.00', 429, 395, 'Subscriber', 'Male', '1905-06-09'),
 (17220, 20983687, '10/1/2018', '10/1/2018', '866', 312, 296, 'Subscriber', 'Female', '1905-05-25'),
 (17221, 20983688, '10/1/2018', '10/1/2018', '474', 87, 58, 'Subscriber', 'Male', '1905-06-04'),
 (17222, 20983689, '10/1/2018', '10/1/2018', '1,282.00', 321, 94, 'Subscriber', 'Male', '1905-05-16'),
 (17223, 20983690, '10/1/2018', '10/1/2018', '689', 230, 127, 'Subscriber', 'Female', '1905-06-09'),
 (17224, 20983691, '10/1/2018', '10/1/2018', '408', 426, 418, 'Subscriber', 'Male', '1905-06-10'),
 (17225, 20983692, '10/1/2018', '10/1/2018', '643', 505, 222, 'Subscriber', 'Male', '1905-06-13'),
 (17226, 20983693, '10/1/2018', '10/1/2018', '1,588.00', 188, 164, 'Subscriber', 'Male', '1905-06-08'),
 (17227, 20983694, '10/1/2018', '10/1/2018', '261', 21, 73, 'Subscriber', 'Male', '1905-06-14'),
 (17228, 20983695, '10/1/2018', '10/1/2018', '151', 418, 420, 'Subscriber', 'Male', '1905-05-19'),
 (17229, 20983696, '10/1/2018', '10/1/2018', '168', 286, 33, 'Subscriber', 'Male', '1905-05-20'),
 (17230, 20983697, '10/1/2018', '10/1/2018', '432', 217, 18, 'Subscriber', 'Male', '1905-06-12'),
 (17231, 20983699, '10/1/2018', '10/1/2018', '1,389.00', 158, 52, 'Subscriber', 'Male', '1905-06-05'),
 (17232, 20983700, '10/1/2018', '10/1/2018', '732', 182, 287, 'Subscriber', 'Male', '1905-06-14'),
 (17233, 20983701, '10/1/2018', '10/1/2018', '861', 35, 49, 'Subscriber', 'Male', '1905-05-10'),
 (17234, 20983703, '10/1/2018', '10/1/2018', '225', 21, 107, 'Subscriber', 'Male', '1905-05-31'),
 (17235, 20983704, '10/1/2018', '10/1/2018', '303', 49, 192, 'Subscriber', 'Male', '1905-06-13'),
 (17236, 20983705, '10/1/2018', '10/1/2018', '366', 351, 417, 'Subscriber', 'Female', '1905-06-14'),
 (17237, 20983706, '10/1/2018', '10/1/2018', '614', 182, 77, 'Subscriber', 'Male', '1905-06-14'),
 (17238, 20983707, '10/1/2018', '10/1/2018', '431', 182, 164, 'Subscriber', 'Male', '1905-06-12'),
 (17239, 20983708, '10/1/2018', '10/1/2018', '189', 182, 620, 'Subscriber', 'Male', '1905-06-12'),
 (17240, 20983709, '10/1/2018', '10/1/2018', '439', 301, 620, 'Subscriber', 'Male', '1905-06-09'),
 (17241, 20983710, '10/1/2018', '10/1/2018', '463', 622, 659, 'Subscriber', 'Female', '1905-06-10'),
 (17242, 20983711, '10/1/2018', '10/1/2018', '262', 96, 88, 'Subscriber', 'Female', '1905-06-15'),
 (17243, 20983712, '10/1/2018', '10/1/2018', '420', 44, 96, 'Subscriber', 'Male', '1905-06-11'),
 (17244, 20983713, '10/1/2018', '10/1/2018', '689', 289, 110, 'Subscriber', 'Female', '1905-06-15'),
 (17245, 20983714, '10/1/2018', '10/1/2018', '999', 502, 229, 'Subscriber', 'Female', '1905-06-06'),
 (17246, 20983715, '10/1/2018', '10/1/2018', '358', 16, 158, 'Subscriber', 'Female', '1905-06-12'),
 (17247, 20983716, '10/1/2018', '10/1/2018', '596', 626, 275, 'Subscriber', 'Male', '1905-06-08'),
 (17248, 20983717, '10/1/2018', '10/1/2018', '1,020.00', 313, 38, 'Subscriber', 'Female', '1905-06-16'),
 (17249, 20983718, '10/1/2018', '10/1/2018', '237', 212, 287, 'Subscriber', 'Male', '1905-05-19'),
 (17250, 20983719, '10/1/2018', '10/1/2018', '391', 350, 346, 'Subscriber', 'Male', '1905-06-09'),
 (17251, 20983721, '10/1/2018', '10/1/2018', '1,286.00', 227, 48, 'Subscriber', 'Female', '1905-06-14'),
 (17252, 20983722, '10/1/2018', '10/1/2018', '140', 113, 225, 'Subscriber', 'Female', '1905-06-13'),
 (17253, 20983723, '10/1/2018', '10/1/2018', '499', 168, 41, 'Subscriber', 'Female', '1905-06-07'),
 (17254, 20983724, '10/1/2018', '10/1/2018', '658', 168, 191, 'Subscriber', 'Male', '1905-06-15'),
 (17255, 20983725, '10/1/2018', '10/1/2018', '381', 96, 283, 'Subscriber', 'Male', '1905-06-15'),
 (17256, 20983726, '10/1/2018', '10/1/2018', '731', 86, 44, 'Subscriber', 'Male', '1905-06-07'),
 (17257, 20983727, '10/1/2018', '10/1/2018', '131', 414, 169, 'Subscriber', 'Male', '1905-06-03'),
 (17258, 20983728, '10/1/2018', '10/1/2018', '579', 92, 346, 'Subscriber', 'Male', '1905-06-11'),
 (17259, 20983729, '10/1/2018', '10/1/2018', '181', 43, 81, 'Subscriber', 'Male', '1905-05-23'),
 (17260, 20983730, '10/1/2018', '10/1/2018', '201', 457, 460, 'Subscriber', 'Male', '1905-05-15'),
 (17261, 20983731, '10/1/2018', '10/1/2018', '280', 43, 98, 'Subscriber', 'Male', '1905-05-11'),
 (17262, 20983732, '10/1/2018', '10/1/2018', '371', 161, 182, 'Subscriber', 'Female', '1905-06-14'),
 (17263, 20983733, '10/1/2018', '10/1/2018', '584', 121, 328, 'Subscriber', 'Male', '1905-06-13'),
 (17264, 20983734, '10/1/2018', '10/1/2018', '406', 301, 140, 'Subscriber', 'Female', '1905-05-11'),
 (17265, 20983735, '10/1/2018', '10/1/2018', '246', 100, 77, 'Subscriber', 'Male', '1905-06-12'),
 (17266, 20983736, '10/1/2018', '10/1/2018', '205', 94, 289, 'Subscriber', 'Female', '1905-06-14'),
 (17267, 20983737, '10/1/2018', '10/1/2018', '195', 73, 68, 'Subscriber', 'Male', '1905-06-04'),
 (17268, 20983738, '10/1/2018', '10/1/2018', '396', 463, 344, 'Subscriber', 'Male', '1905-05-14'),
 (17269, 20983739, '10/1/2018', '10/1/2018', '319', 327, 13, 'Subscriber', 'Female', '1905-06-14'),
 (17270, 20983740, '10/1/2018', '10/1/2018', '2,321.00', 506, 145, 'Subscriber', 'Female', '1905-06-11'),
 (17271, 20983742, '10/1/2018', '10/1/2018', '277', 312, 304, 'Subscriber', 'Male', '1905-06-13'),
 (17272, 20983743, '10/1/2018', '10/1/2018', '266', 13, 127, 'Subscriber', 'Male', '1905-06-06'),
 (17273, 20983744, '10/1/2018', '10/1/2018', '306', 488, 483, 'Subscriber', 'Female', '1905-06-15'),

In [126]:

engine.execute("SELECT * FROM stations").fetchall()

[(0, 102, 'Stony Island Ave & 67th St', None, 11, 11, 'In Service', 41.773458500000004, -87.58533974, '(41.77345849948, -87.5853397391)'),
 (1, 103, 'Clinton St & Polk St', None, 15, 15, 'In Service', 41.87146652, -87.64094913, '(41.87146651779, -87.6409491327)'),
 (2, 11, 'Jeffery Blvd & 71st St', None, 11, 11, 'In Service', 41.76663824, -87.57645011, '(41.76663823695, -87.5764501141)'),
 (3, 12, 'South Shore Dr & 71st St', None, 15, 15, 'In Service', 41.76640946, -87.56568757, '(41.7664094567, -87.5656875719)'),
 (4, 132, 'Wentworth Ave & 24th St (Temp)', None, 15, 15, 'In Service', 41.85008369, -87.63214052, '(41.85008369347577, -87.6321405172348)'),
 (5, 133, 'Kingsbury St & Kinzie St', None, 31, 31, 'In Service', 41.88917683, -87.63850577, '(41.88917683258, -87.6385057718)'),
 (6, 145, 'Mies van der Rohe Way & Chestnut St', None, 19, 19, 'In Service', 41.89858665, -87.62191523, '(41.8985866514, -87.6219152258)'),
 (7, 156, 'Clark St & Wellington Ave', None, 15, 15, 'In Service', 41.93649682, -87.64753866, '(41.9364968219, -87.6475386582)'),
 (8, 157, 'Lake Shore Dr & Wellington Ave', None, 15, 15, 'In Service', 41.93668845, -87.63682902, '(41.9366884494997, -87.63682901859283)'),
 (9, 161, 'Rush St & Superior St', None, 23, 23, 'In Service', 41.89576475, -87.62590803, '(41.89576474564, -87.6259080327)'),
 (10, 172, 'Rush St & Cedar St', None, 11, 11, 'In Service', 41.902308700000006, -87.62769053, '(41.90230870122, -87.627690528)'),
 (11, 2, 'Buckingham Fountain', None, 39, 39, 'In Service', 41.87651123, -87.62054801, '(41.87651122881695, -87.62054800987242)'),
 (12, 239, 'Western Ave & Leland Ave', None, 15, 15, 'In Service', 41.96581646, -87.68649817, '(41.96581646001197, -87.68649816513062)'),
 (13, 259, 'California Ave & Francis Pl (Temp)', None, 15, 15, 'In Service', 41.91849115, -87.6974228, '(41.91849115368695, -87.69742280244827)'),
 (14, 270, 'Stony Island Ave & 75th St', None, 11, 11, 'In Service', 41.75866967, -87.58688287, '(41.7586696704, -87.586882871)'),
 (15, 286, 'Franklin St & Adams St (Temp)', None, 15, 15, 'In Service', 41.87943409, -87.63550401, '(41.87943409140013, -87.63550400733948)'),
 (16, 3, 'Shedd Aquarium', None, 55, 55, 'In Service', 41.86722596, -87.61535539, '(41.86722595682, -87.6153553902)'),
 (17, 31, 'Franklin St & Chicago Ave', None, 23, 23, 'In Service', 41.89674697, -87.63566762, '(41.896746973093805, -87.63566762208939)'),
 (18, 319, 'Greenview Ave & Diversey Pkwy', None, 15, 15, 'In Service', 41.93258963, -87.66593635, '(41.93258963429789, -87.66593635082245)'),
 (19, 34, 'Cannon Dr & Fullerton Ave', None, 15, 15, 'In Service', 41.92675599, -87.63442879, '(41.9267559875, -87.6344287848)'),
 (20, 348, 'California Ave & 21st St', None, 15, 15, 'In Service', 41.85380407, -87.69574240000001, '(41.8538040657915, -87.69574239850043)'),
 (21, 352, 'Jeffery Blvd & 67th St', None, 11, 11, 'In Service', 41.77351755, -87.57714283, '(41.77351755125, -87.5771428255)'),
 (22, 354, 'Sheridan Rd & Greenleaf Ave', None, 15, 15, 'In Service', 42.01058656, -87.6624121, '(42.01058656284, -87.6624120948)'),
 (23, 356, 'Stony Island Ave & 71st St', None, 11, 11, 'In Service', 41.76649294, -87.58646088, '(41.7664929373, -87.5864608775)'),
 (24, 359, 'Larrabee St & Division St', None, 23, 23, 'In Service', 41.90348607, -87.64335349, '(41.90348607004, -87.6433534936)'),
 (25, 36, 'Franklin St & Jackson Blvd', None, 39, 39, 'In Service', 41.87770796, -87.63532114, '(41.8777079559, -87.6353211408)'),
 (26, 364, 'Larrabee St & Oak St', None, 19, 19, 'In Service', 41.90021949, -87.64298547, '(41.90021949323, -87.6429854676)'),
 (27, 366, 'Loomis St & Archer Ave', None, 11, 11, 'In Service', 41.84163254, -87.65743495, '(41.84163253965, -87.6574349533)'),
 (28, 367, 'Racine Ave & 35th St', None, 15, 15, 'In Service', 41.83069611, -87.65597591, '(41.83069611252, -87.6559759116)'),
 (29, 368, 'Ashland Ave & Archer Ave', None, 15, 15, 'In Service', 41.83920868, -87.66560986, '(41.83920868403, -87.6656098589)'),
 (30, 369, 'Wood St & 35th St', None, 11, 11, 'In Service', 41.83010465, -87.67029831, '(41.83010465416, -87.6702983089)'),
 (31, 37, 'Dearborn St & Adams St', None, 19, 19, 'In Service', 41.87935636, -87.62979104, '(41.8793563587, -87.6297910363)'),
 (32, 370, 'Calumet Ave & 21st St', None, 15, 15, 'In Service', 41.85418425, -87.61915374, '(41.85418424947, -87.6191537415)'),
 (33, 373, 'Kedzie Ave & Chicago Ave', None, 11, 11, 'In Service', 41.8954653, -87.70612788, '(41.89546530305, -87.7061278837)'),
 (34, 374, 'Western Ave & Walton St', None, 23, 23, 'In Service', 41.89841769, -87.68659602, '(41.89841768945, -87.6865960164)'),
 (35, 375, 'Sacramento Blvd & Franklin Blvd', None, 11, 11, 'In Service', 41.89046879, -87.70260751, '(41.89046879243862, -87.70260751247406)'),
 (36, 376, 'Artesian Ave & Hubbard St', None, 35, 35, 'In Service', 41.88949182, -87.68821937, '(41.88949181977, -87.6882193648)'),
 (37, 377, 'Kedzie Ave & Lake St', None, 15, 15, 'In Service', 41.88460329, -87.70630374, '(41.88460328501, -87.7063037436)'),
 (38, 378, 'California Ave & Lake St', None, 11, 11, 'In Service', 41.88445396, -87.69629814, '(41.88445395657, -87.6962981368)'),
 (39, 38, 'Clark St & Lake St', None, 27, 27, 'In Service', 41.88602083, -87.63087606, '(41.88602082773, -87.6308760584)'),
 (40, 381, 'Western Ave & Monroe St', None, 15, 15, 'In Service', 41.87978771, -87.68611281, '(41.8797877089, -87.686112808)'),
 (41, 382, 'Western Ave & Congress Pkwy', None, 19, 19, 'In Service', 41.87474885, -87.68644528, '(41.87474885079, -87.6864452757)'),
 (42, 384, 'Halsted St & 51st St', None, 11, 11, 'In Service', 41.80183164, -87.6452139, '(41.80183164049, -87.645213904)'),
 (43, 386, 'Halsted St & 56th St', None, 11, 11, 'In Service', 41.79292965, -87.64499006, '(41.79292964599, -87.6449900565)'),
 (44, 388, 'Halsted St & 63rd St', None, 11, 11, 'In Service', 41.77938114, -87.64462082, '(41.77938114228, -87.6446208145)'),
 (45, 39, 'Wabash Ave & Adams St', None, 23, 23, 'In Service', 41.87947235, -87.62568861, '(41.87947235235, -87.6256886059)'),
 (46, 390, 'Wentworth Ave & 63rd St', None, 11, 11, 'In Service', 41.78007963, -87.62974631, '(41.78007963264, -87.6297463052)'),
 (47, 391, 'Halsted St & 69th St', None, 11, 11, 'In Service', 41.76906172, -87.64461358, '(41.76906172032, -87.6446135779)'),
 (48, 392, 'Perry Ave & 69th St', None, 11, 11, 'In Service', 41.76929309, -87.62819593, '(41.76929308995, -87.6281959291)'),
 (49, 393, 'Calumet Ave & 71st St', None, 11, 11, 'In Service', 41.76550801, -87.61691793, '(41.76550800581, -87.616917925)'),
 (50, 395, 'Jeffery Blvd & 76th St', None, 11, 11, 'In Service', 41.75712007, -87.57583936, '(41.75712006802, -87.5758393587)'),
 (51, 398, 'Rainbow Beach', None, 15, 15, 'In Service', 41.75787145, -87.54938625, '(41.75787144829, -87.54938625)'),
 (52, 399, 'South Shore Dr & 74th St', None, 11, 11, 'In Service', 41.76218896, -87.55927465, '(41.76218896038, -87.55927465)'),
 (53, 403, 'Wentworth Ave & 33rd St', None, 15, 15, 'In Service', 41.83452989, -87.63182298, '(41.83452988563, -87.6318229814)'),
 (54, 406, 'Lake Park Ave & 35th St', None, 19, 19, 'In Service', 41.83127424, -87.6087992, '(41.83127423549, -87.6087991946)'),
 (55, 407, 'State St & Pershing Rd', None, 11, 11, 'In Service', 41.82301524, -87.62656802, '(41.82301523798, -87.6265680185)'),
 (56, 409, 'Shields Ave & 43rd St', None, 11, 11, 'In Service', 41.81620768, -87.63481935, '(41.81620767856, -87.6348193497)'),
 (57, 41, 'Federal St & Polk St', None, 19, 19, 'In Service', 41.87207763, -87.62954377, '(41.87207763285, -87.6295437729)'),
 (58, 410, 'Prairie Ave & 43rd St', None, 15, 15, 'In Service', 41.81665889, -87.61941246, '(41.81665889302, -87.6194124619)'),
 (59, 411, 'Halsted St & 47th Pl', None, 11, 11, 'In Service', 41.80813392, -87.64561655, '(41.80813391481, -87.6456165545)'),
 (60, 412, 'Princeton Ave & 47th St', None, 11, 11, 'In Service', 41.80931771, -87.63344929, '(41.80931770924, -87.633449288)'),
 (61, 413, 'Woodlawn Ave & Lake Park Ave', None, 15, 15, 'In Service', 41.81409271, -87.59700515, '(41.81409271048, -87.5970051479)'),
 (62, 415, 'Calumet Ave & 51st St', None, 11, 11, 'In Service', 41.80229465, -87.61805358, '(41.80229465088, -87.6180535802)'),
 (63, 418, 'Ellis Ave & 53rd St', None, 11, 11, 'In Service', 41.79933626, -87.60095812, '(41.79933626261, -87.6009581145)'),
 (64, 419, 'Lake Park Ave & 53rd St', None, 15, 15, 'In Service', 41.79949429, -87.5864499, '(41.79949429373, -87.5864498959)'),
 (65, 420, 'Ellis Ave & 55th St', None, 19, 19, 'In Service', 41.79430062, -87.60144977, '(41.79430062054, -87.6014497734)'),
 (66, 421, 'MLK Jr Dr & 56th St', None, 11, 11, 'In Service', 41.79342946, -87.61585326, '(41.79342945658, -87.6158532619)'),
 (67, 422, 'DuSable Museum', None, 11, 11, 'In Service', 41.79156801, -87.60785218, '(41.79156801058, -87.6078521774)'),
 (68, 424, 'Museum of Science and Industry', None, 27, 27, 'In Service', 41.79172821, -87.58394501, '(41.79172820953, -87.583945009)'),
 (69, 425, 'Harper Ave & 59th St', None, 15, 15, 'In Service', 41.78794281, -87.58831517, '(41.78794281287, -87.5883151702)'),
 (70, 426, 'Ellis Ave & 60th St', None, 19, 19, 'In Service', 41.78509715, -87.60107276, '(41.78509714636, -87.6010727606)'),
 (71, 427, 'Cottage Grove Ave & 63rd St', None, 15, 15, 'In Service', 41.78059902, -87.60611239, '(41.78059901484, -87.606112388)'),
 (72, 428, 'Dorchester Ave & 63rd St', None, 11, 11, 'In Service', 41.78040565, -87.59141599, '(41.7804056457, -87.5914159893)'),
 (73, 43, 'Michigan Ave & Washington St', None, 43, 43, 'In Service', 41.88398407, -87.62468398, '(41.8839840647265, -87.6246839761734)'),
 (74, 430, 'MLK Jr Dr & 63rd St', None, 11, 11, 'In Service', 41.78008064, -87.61594286, '(41.78008063659, -87.6159428567)'),
 (75, 431, 'Eberhart Ave & 61st St', None, 11, 11, 'In Service', 41.78414169, -87.61330783, '(41.78414169317, -87.6133078304)'),
 (76, 433, 'Kedzie Ave & Harrison St', None, 11, 11, 'In Service', 41.87359968, -87.70487075, '(41.87359967462, -87.7048707493)'),
 (77, 434, 'Ogden Ave & Roosevelt Rd', None, 19, 19, 'In Service', 41.86650148, -87.68469707, '(41.86650148316, -87.68469707)'),
 (78, 435, 'Kedzie Ave & Roosevelt Rd', None, 11, 11, 'In Service', 41.86649278, -87.70649618, '(41.86649278172, -87.7064961757)'),
 (79, 438, 'Central Park Ave & Ogden Ave', None, 15, 15, 'In Service', 41.85420431, -87.71540584, '(41.85420431327, -87.7154058381)'),
 (80, 439, 'Kedzie Ave & 21st St', None, 11, 11, 'In Service', 41.85353363, -87.70507303, '(41.85353363213, -87.7050730318)'),
 (81, 44, 'State St & Randolph St', None, 27, 27, 'In Service', 41.8847302, -87.62773357, '(41.8847302006, -87.6277335692)'),
 (82, 441, 'Kedzie Ave & 24th St', None, 11, 11, 'In Service', 41.84819095, -87.70541375, '(41.84819094491, -87.7054137458)'),
 (83, 443, 'Millard Ave & 26th St', None, 7, 7, 'In Service', 41.84456685, -87.71591031, '(41.84456684891, -87.7159103081)'),
 (84, 444, 'Albany Ave & 26th St', None, 11, 11, 'In Service', 41.84447501, -87.70201301, '(41.84447501366, -87.7020130128)'),
 (85, 445, 'California Ave & 26th St', None, 11, 11, 'In Service', 41.84404003, -87.69529592, '(41.84404003127, -87.6952959227)'),
 (86, 446, 'Western Ave & 28th St', None, 11, 11, 'In Service', 41.84151771, -87.68513144, '(41.84151770807, -87.6851314409)'),
 (87, 447, 'Glenwood Ave & Morse Ave', None, 15, 15, 'In Service', 42.00797192, -87.66550239, '(42.00797192287, -87.6655023944)'),
 (88, 448, 'Warren Park East', None, 11, 11, 'In Service', 42.00454962, -87.68066615, '(42.00454962194, -87.6806661451)'),
 (89, 449, 'Clark St & Columbia Ave', None, 15, 15, 'In Service', 42.00445063, -87.67240241, '(42.00445062934, -87.6724024047)'),
 (90, 453, 'Clark St & Schreiber Ave', None, 15, 15, 'In Service', 41.99925182, -87.67137734, '(41.99925182186, -87.6713773393)'),
 (91, 454, 'Broadway & Granville Ave', None, 23, 23, 'In Service', 41.99477969, -87.66028454, '(41.9947796884, -87.6602845349)'),
 (92, 455, 'Maplewood Ave & Peterson Ave', None, 11, 11, 'In Service', 41.99023603, -87.69336964, '(41.99023602867, -87.6933696402)'),
 (93, 457, 'Clark St & Elmdale Ave', None, 15, 15, 'In Service', 41.99051756, -87.66983359999999, '(41.99051755556753, -87.66983360052109)'),
 (94, 458, 'Broadway & Thorndale Ave', None, 19, 19, 'In Service', 41.98974251, -87.66014062, '(41.98974251144, -87.6601406209)'),
 (95, 459, 'Lakefront Trail & Bryn Mawr Ave', None, 19, 19, 'In Service', 41.984036700000004, -87.65231047, '(41.98403669612, -87.6523104689)'),
 (96, 461, 'Broadway & Ridge Ave', None, 15, 15, 'In Service', 41.98404461, -87.66027383, '(41.9840446107, -87.6602738295)'),
 (97, 463, 'Clark St & Berwyn Ave', None, 19, 19, 'In Service', 41.97799665, -87.66804711, '(41.9779966544, -87.6680471047)'),
 (98, 464, 'Damen Ave & Foster Ave', None, 15, 15, 'In Service', 41.97561481, -87.67945904, '(41.97561480459, -87.6794590387)'),
 (99, 466, 'Ridge Blvd & Touhy Ave', None, 11, 11, 'In Service', 42.01213228, -87.68291264, '(42.01213227742, -87.6829126443)'),
 (100, 467, 'Western Ave & Lunt Ave', None, 15, 15, 'In Service', 42.00859439999999, -87.69049224, '(42.0085943972, -87.6904922389)'),
 (101, 468, 'Budlong Woods Library', None, 11, 11, 'In Service', 41.98366471, -87.69642256, '(41.98366470886, -87.6964225611)'),
 (102, 469, 'St. Louis Ave & Balmoral Ave', None, 15, 15, 'In Service', 41.98039424, -87.71611496, '(41.98039423475, -87.7161149615)'),
 (103, 471, 'Francisco Ave & Foster Ave', None, 15, 15, 'In Service', 41.97563273, -87.70141944, '(41.97563272521, -87.7014194389)'),
 (104, 472, 'Lincoln Ave & Winona St', None, 15, 15, 'In Service', 41.974911299999995, -87.69250256, '(41.97491129677, -87.6925025594)'),
 (105, 474, 'Christiana Ave & Lawrence Ave', None, 15, 15, 'In Service', 41.96835449, -87.71183067, '(41.96835449363, -87.7118306675)'),
 (106, 476, 'Kedzie Ave & Leland Ave', None, 15, 15, 'In Service', 41.96668636, -87.70805198, '(41.96668636205, -87.7080519806)'),
 (107, 478, 'Rockwell St & Eastwood Ave', None, 15, 15, 'In Service', 41.96590014, -87.69363849, '(41.96590013976, -87.6936384935)'),
 (108, 479, 'Drake Ave & Montrose Ave', None, 15, 15, 'In Service', 41.96115408, -87.71656907, '(41.96115407569, -87.7165690733)'),
 (109, 482, 'Campbell Ave & Montrose Ave', None, 15, 15, 'In Service', 41.96152593, -87.69116504, '(41.96152593287, -87.6911650414)'),
 (110, 484, 'Monticello Ave & Irving Park Rd', None, 15, 15, 'In Service', 41.95400484, -87.71912818, '(41.95400483876, -87.7191281797)'),
 (111, 485, 'Sawyer Ave & Irving Park Rd', None, 15, 15, 'In Service', 41.95358618, -87.7093108, '(41.95358617895, -87.7093107999)'),
 (112, 486, 'Oakley Ave & Irving Park Rd', None, 15, 15, 'In Service', 41.95434085, -87.68607962, '(41.95434085219, -87.6860796243)'),
 (113, 487, 'California Ave & Byron St', None, 19, 19, 'In Service', 41.95216219, -87.69805111, '(41.95216219326, -87.698051113)'),
 (114, 49, 'Dearborn St & Monroe St', None, 39, 39, 'In Service', 41.88131982, -87.62952092, '(41.881319815, -87.6295209193)'),
 (115, 490, 'Troy St & Elston Ave', None, 15, 15, 'In Service', 41.94524357, -87.7066499, '(41.94524356848, -87.7066499009)'),
 (116, 491, 'Talman Ave & Addison St', None, 15, 15, 'In Service', 41.94663583, -87.69461476, '(41.9466358306, -87.694614758)'),
 (117, 494, 'Kedzie Ave & Bryn Mawr Ave', None, 15, 15, 'In Service', 41.98239709, -87.70892252, '(41.98239708485, -87.7089225202)'),
 (118, 495, 'Keystone Ave & Montrose Ave', None, 11, 11, 'In Service', 41.96110802, -87.72897009999998, '(41.96110801623, -87.7289701012)'),
 (119, 498, 'California Ave & Fletcher St', None, 19, 19, 'In Service', 41.93842879, -87.69800776, '(41.93842879148, -87.698007756)'),
 (120, 499, 'Kosciuszko Park', None, 15, 15, 'In Service', 41.93058537, -87.72377736, '(41.93058537138, -87.7237773635)'),
 (121, 50, 'Clark St & Ida B Wells Dr', None, 35, 35, 'In Service', 41.87593267, -87.63058454, '(41.8759326655, -87.6305845355)'),
 (122, 500, 'Central Park Ave & Elbridge Ave', None, 15, 15, 'In Service', 41.93533728, -87.71688929, '(41.93533728263, -87.7168892935)'),
 (123, 501, 'Richmond St & Diversey Ave', None, 15, 15, 'In Service', 41.93190197, -87.70119513, '(41.93190196886, -87.7011951301)'),
 (124, 503, 'Drake Ave & Fullerton Ave', None, 15, 15, 'In Service', 41.92439882, -87.71544104, '(41.924398819, -87.7154410355)'),
 (125, 504, 'Campbell Ave & Fullerton Ave', None, 15, 15, 'In Service', 41.92463247, -87.68930701, '(41.92463247165, -87.6893070063)'),
 (126, 505, 'Winchester Ave & Elston Ave', None, 15, 15, 'In Service', 41.92409085, -87.67646008, '(41.92409085038, -87.6764600747)'),
 (127, 506, 'Spaulding Ave & Armitage Ave', None, 15, 15, 'In Service', 41.91710804, -87.71022096, '(41.917108034789315, -87.71022096276283)'),
 (128, 507, 'Humboldt Blvd & Armitage Ave', None, 19, 19, 'In Service', 41.91751339, -87.70180896, '(41.91751339399, -87.7018089555)'),
 (129, 508, 'Central Park Ave & North Ave', None, 15, 15, 'In Service', 41.90965688, -87.71663195, '(41.90965687563, -87.7166319516)'),
 (130, 509, 'Troy St & North Ave', None, 15, 15, 'In Service', 41.909769299999994, -87.70528049, '(41.90976930169, -87.7052804871)'),
 (131, 510, 'Spaulding Ave & Division St', None, 11, 11, 'In Service', 41.90270659, -87.70921957, '(41.90270659438, -87.709219571)'),
 (132, 511, 'Albany Ave & Bloomingdale Ave', None, 15, 15, 'In Service', 41.91402671, -87.70512646, '(41.91402671273, -87.705126462)'),
 (133, 54, 'Ogden Ave & Chicago Ave', None, 19, 19, 'In Service', 41.89636246, -87.65406127, '(41.896362458, -87.6540612729)'),
 (134, 57, 'Clinton St & Roosevelt Rd', None, 15, 15, 'In Service', 41.86711778, -87.64108796, '(41.8671177825, -87.6410879593)'),
 (135, 60, 'Dayton St & North Ave', None, 19, 19, 'In Service', 41.91057804, -87.64942193, '(41.9105780349, -87.6494219288)'),
 (136, 62, 'McCormick Place', None, 27, 27, 'In Service', 41.85137517, -87.61883465, '(41.8513751729, -87.6188346489)'),
 (137, 638, 'Clinton St & Jackson Blvd', None, 23, 23, 'In Service', 41.87811603, -87.63983846, '(41.87811603010527, -87.63983845710754)'),
 (138, 67, 'Sheffield Ave & Fullerton Ave', None, 27, 27, 'In Service', 41.92560188, -87.65370804, '(41.9256018819, -87.6537080423)'),
 (139, 672, 'Franklin St & Illinois St', None, 11, 11, 'In Service', 41.89102331, -87.63547987, '(41.89102331025185, -87.63547986745834)'),
 (140, 673, 'Lincoln Park Conservatory', None, 31, 31, 'In Service', 41.92393131, -87.63582453, '(41.92393131136619, -87.63582453131676)'),
 (141, 69, 'Damen Ave & Pierce Ave', None, 23, 23, 'In Service', 41.90939601, -87.67769193, '(41.9093960065, -87.6776919292)'),
 (142, 7, 'Field Blvd & South Water St', None, 19, 19, 'In Service', 41.88634906, -87.61751655, '(41.88634906269, -87.6175165471)'),
 (143, 74, 'Kingsbury St & Erie St', None, 23, 23, 'In Service', 41.89380806, -87.64169723, '(41.89380805624359, -87.64169722795485)'),
 (144, 89, 'Financial Pl & Ida B Wells Dr', None, 31, 31, 'In Service', 41.87502363, -87.63309404, '(41.8750236280333, -87.6330940425396)'),
 (145, 96, 'Desplaines St & Randolph St', None, 23, 23, 'In Service', 41.88461619, -87.64457059, '(41.88461618962, -87.6445705849)'),
 (146, 134, 'Peoria St & Jackson Blvd', None, 23, 23, 'In Service', 41.877641600000004, -87.64961779, '(41.8776415962753, -87.64961779117584)'),
 (147, 353, 'Clark St & Touhy Ave', None, 15, 15, 'In Service', 42.01256012, -87.67436712, '(42.01256011541, -87.6743671152)'),
 (148, 365, 'Halsted St & North Branch St', None, 15, 15, 'In Service', 41.89936844, -87.64847988, '(41.89936843921, -87.6484798752)'),
 (149, 40, 'LaSalle St & Adams St', None, 15, 15, 'In Service', 41.87934437, -87.63198522, '(41.87934437346, -87.6319852213)'),
 (150, 56, 'Desplaines St & Kinzie St', None, 27, 27, 'In Service', 41.88871604, -87.64444785, '(41.888716036, -87.6444478533)'),
 (151, 71, 'Morgan St & Lake St', None, 23, 23, 'In Service', 41.88548331, -87.65230486, '(41.8854833079, -87.6523048564)'),