In [5]:
# Import Dependencies
import pandas as pd
import numpy as np
import sqlite3
from sqlalchemy import create_engine
engine = create_engine('sqlite:///data/hist_trips.sqlite', echo=False)

In [6]:
# Capture all data from the hist_trips table inside hist_trips.sqlite
riders_tbl = pd.read_sql("SELECT * FROM hist_trips", con=engine)
riders_tbl.head()

,index,trip_id,start_time,end_time,tripduration,from_station_id,to_station_id,usertype,gender,birthyear
0,0,22178529,4/1/2019,4/1/2019,446,81,56,Subscriber,Male,5/28/2005
1,1,22178530,4/1/2019,4/1/2019,"1,048.00",317,59,Subscriber,Female,6/6/2005
2,2,22178531,4/1/2019,4/1/2019,252,283,174,Subscriber,Male,6/12/2005
3,3,22178532,4/1/2019,4/1/2019,357,26,133,Subscriber,Male,6/15/2005
4,4,22178533,4/1/2019,4/1/2019,"1,007.00",202,129,Subscriber,Male,6/14/2005

In [7]:
# Capture alld data from the stations table inside hist_trips.sqlite
stations_tbl = pd.read_sql("SELECT * FROM stations", con=engine)
stations_tbl.head()

,index,ID,Station Name,Address,Total Docks,Docks in Service,Status,Latitude,Longitude,Location
0,0,102,Stony Island Ave & 67th St,None,11,11,In Service,41.773459,-87.585340,"(41.77345849948, -87.5853397391)"
1,1,103,Clinton St & Polk St,None,15,15,In Service,41.871467,-87.640949,"(41.87146651779, -87.6409491327)"
2,2,11,Jeffery Blvd & 71st St,None,11,11,In Service,41.766638,-87.576450,"(41.76663823695, -87.5764501141)"
3,3,12,South Shore Dr & 71st St,None,15,15,In Service,41.766409,-87.565688,"(41.7664094567, -87.5656875719)"
4,4,132,Wentworth Ave & 24th St (Temp),None,15,15,In Service,41.850084,-87.632141,"(41.85008369347577, -87.6321405172348)"

In [8]:
# Join station name on from station id
from_station_name = pd.merge(riders_tbl, stations_tbl, left_on='from_station_id', right_on='ID', how='left')
from_station_name.head()

,index_x,trip_id,start_time,end_time,tripduration,from_station_id,to_station_id,usertype,gender,birthyear,index_y,ID,Station Name,Address,Total Docks,Docks in Service,Status,Latitude,Longitude,Location
0,0,22178529,4/1/2019,4/1/2019,446,81,56,Subscriber,Male,5/28/2005,333.0,81.0,Daley Center Plaza,None,39.0,39.0,In Service,41.884241,-87.629634,"(41.884241, -87.629634)"
1,1,22178530,4/1/2019,4/1/2019,"1,048.00",317,59,Subscriber,Female,6/6/2005,292.0,317.0,Wood St & Taylor St,None,23.0,23.0,In Service,41.869154,-87.671045,"(41.869154, -87.671045)"
2,2,22178531,4/1/2019,4/1/2019,252,283,174,Subscriber,Male,6/12/2005,378.0,283.0,LaSalle St & Jackson Blvd,None,35.0,35.0,In Service,41.878166,-87.631929,"(41.878166, -87.631929)"
3,3,22178532,4/1/2019,4/1/2019,357,26,133,Subscriber,Male,6/15/2005,458.0,26.0,McClurg Ct & Illinois St,None,31.0,31.0,In Service,41.890359,-87.617532,"(41.890359, -87.617532)"
4,4,22178533,4/1/2019,4/1/2019,"1,007.00",202,129,Subscriber,Male,6/14/2005,238.0,202.0,Halsted St & 18th St,None,15.0,15.0,In Service,41.857499,-87.646277,"(41.857499, -87.646277)"

In [9]:
# Peform another join to also add station name for the to station id
station_names = pd.merge(from_station_name, stations_tbl, left_on='to_station_id', right_on='ID', how='left')
station_names.head()

,index_x,trip_id,start_time,end_time,tripduration,from_station_id,to_station_id,usertype,gender,birthyear,...,index,ID_y,Station Name_y,Address_y,Total Docks_y,Docks in Service_y,Status_y,Latitude_y,Longitude_y,Location_y
0,0,22178529,4/1/2019,4/1/2019,446,81,56,Subscriber,Male,5/28/2005,...,150.0,56.0,Desplaines St & Kinzie St,None,27.0,27.0,In Service,41.888716,-87.644448,"(41.888716036, -87.6444478533)"
1,1,22178530,4/1/2019,4/1/2019,"1,048.00",317,59,Subscriber,Female,6/6/2005,...,270.0,59.0,Wabash Ave & Roosevelt Rd,None,23.0,23.0,In Service,41.867227,-87.625961,"(41.867227, -87.625961)"
2,2,22178531,4/1/2019,4/1/2019,252,283,174,Subscriber,Male,6/12/2005,...,413.0,174.0,Canal St & Madison St,None,35.0,35.0,In Service,41.882091,-87.639833,"(41.882091, -87.639833)"
3,3,22178532,4/1/2019,4/1/2019,357,26,133,Subscriber,Male,6/15/2005,...,5.0,133.0,Kingsbury St & Kinzie St,None,31.0,31.0,In Service,41.889177,-87.638506,"(41.88917683258, -87.6385057718)"
4,4,22178533,4/1/2019,4/1/2019,"1,007.00",202,129,Subscriber,Male,6/14/2005,...,226.0,129.0,Blue Island Ave & 18th St,None,15.0,15.0,In Service,41.857556,-87.661535,"(41.857556, -87.661535)"

In [10]:
# Select the columns you want to use.
df = station_names[['Station Name_x', 'Station Name_y', 'Location_x', 'Location_y','gender', 'tripduration']]
df.head()

,Station Name_x,Station Name_y,Location_x,Location_y,gender,tripduration
0,Daley Center Plaza,Desplaines St & Kinzie St,"(41.884241, -87.629634)","(41.888716036, -87.6444478533)",Male,446
1,Wood St & Taylor St,Wabash Ave & Roosevelt Rd,"(41.869154, -87.671045)","(41.867227, -87.625961)",Female,"1,048.00"
2,LaSalle St & Jackson Blvd,Canal St & Madison St,"(41.878166, -87.631929)","(41.882091, -87.639833)",Male,252
3,McClurg Ct & Illinois St,Kingsbury St & Kinzie St,"(41.890359, -87.617532)","(41.88917683258, -87.6385057718)",Male,357
4,Halsted St & 18th St,Blue Island Ave & 18th St,"(41.857499, -87.646277)","(41.857556, -87.661535)",Male,"1,007.00"

In [11]:
df.dtypes

Station Name_x    object
Station Name_y    object
Location_x        object
Location_y        object
gender            object
tripduration      object
dtype: object

In [12]:
df["tripduration"] = df["tripduration"].str.replace(",","").astype(float)

C:\Users\bchee\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [7]:
#df["tripduration"] = pd.to_numeric(df["tripduration"], errors = 'coerce')

C:\Users\bchee\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [13]:
df_trips = df.astype({"Station Name_x": str, "Station Name_y": str, "gender": str, "tripduration": float})
df.head()
df.count()

Station Name_x    807416
Station Name_y    807392
Location_x        807416
Location_y        807392
gender            807430
tripduration      807430
dtype: int64

In [14]:
# Drop rows with NAN's
df_trips = df.dropna()
df_trips.count()

Station Name_x    807380
Station Name_y    807380
Location_x        807380
Location_y        807380
gender            807380
tripduration      807380
dtype: int64

In [15]:
# Find the average drip duration
df_gender = df_trips.groupby(['Station Name_x', 'Station Name_y', 'Location_x', 'Location_y', 'gender']).mean().reset_index()

df_gender.head()

,Station Name_x,Station Name_y,Location_x,Location_y,gender,tripduration
0,2112 W Peterson Ave,2112 W Peterson Ave,"(41.991178, -87.683593)","(41.991178, -87.683593)",Female,62.000000
1,2112 W Peterson Ave,2112 W Peterson Ave,"(41.991178, -87.683593)","(41.991178, -87.683593)",Male,1190.000000
2,2112 W Peterson Ave,Broadway & Argyle St,"(41.991178, -87.683593)","(41.973815, -87.65966)",Male,957.000000
3,2112 W Peterson Ave,Broadway & Granville Ave,"(41.991178, -87.683593)","(41.9947796884, -87.6602845349)",Male,483.000000
4,2112 W Peterson Ave,Broadway & Ridge Ave,"(41.991178, -87.683593)","(41.9840446107, -87.6602738295)",Male,1204.666667

In [16]:
df_gender["tripduration"].describe()

count    1.093150e+05
mean     1.370088e+03
std      1.845796e+04
min      6.100000e+01
25%      6.803333e+02
50%      1.041000e+03
75%      1.511859e+03
max      4.439590e+06
Name: tripduration, dtype: float64

In [17]:
df_gender = df_gender.rename(columns = {'Station Name_x': 'Station_Name_x', 'Station Name_y':'Station_Name_y', 'tripduration': 'Avg_duration'})
df_gender = df_gender.astype({"Avg_duration": int})
df_gender['Avg_duration'] = df_gender['Avg_duration'] / 60
df_gender.head()

,Station_Name_x,Station_Name_y,Location_x,Location_y,gender,Avg_duration
0,2112 W Peterson Ave,2112 W Peterson Ave,"(41.991178, -87.683593)","(41.991178, -87.683593)",Female,1.033333
1,2112 W Peterson Ave,2112 W Peterson Ave,"(41.991178, -87.683593)","(41.991178, -87.683593)",Male,19.833333
2,2112 W Peterson Ave,Broadway & Argyle St,"(41.991178, -87.683593)","(41.973815, -87.65966)",Male,15.950000
3,2112 W Peterson Ave,Broadway & Granville Ave,"(41.991178, -87.683593)","(41.9947796884, -87.6602845349)",Male,8.050000
4,2112 W Peterson Ave,Broadway & Ridge Ave,"(41.991178, -87.683593)","(41.9840446107, -87.6602738295)",Male,20.066667

In [18]:
df_count = df_trips.groupby(['Station Name_x', 'Station Name_y', 'Location_x', 'Location_y', 'gender']).count().reset_index()
df_count = df_count.rename(columns = {'Station Name_x': 'Station_Name_x', 'Station Name_y':'Station_Name_y','tripduration': 'Trip_counts'})
df_count.head()

,Station_Name_x,Station_Name_y,Location_x,Location_y,gender,Trip_counts
0,2112 W Peterson Ave,2112 W Peterson Ave,"(41.991178, -87.683593)","(41.991178, -87.683593)",Female,1
1,2112 W Peterson Ave,2112 W Peterson Ave,"(41.991178, -87.683593)","(41.991178, -87.683593)",Male,1
2,2112 W Peterson Ave,Broadway & Argyle St,"(41.991178, -87.683593)","(41.973815, -87.65966)",Male,1
3,2112 W Peterson Ave,Broadway & Granville Ave,"(41.991178, -87.683593)","(41.9947796884, -87.6602845349)",Male,1
4,2112 W Peterson Ave,Broadway & Ridge Ave,"(41.991178, -87.683593)","(41.9840446107, -87.6602738295)",Male,3

In [23]:
df_merge = pd.merge(df_gender, df_count, on=['Station_Name_x', 'Station_Name_y', 'Location_x', 'Location_y', 'gender'], how='outer')
# df_merge = df_merge.nlargest(10,'Trip_counts')
df_merge.head()

,Station_Name_x,Station_Name_y,Location_x,Location_y,gender,Avg_duration,Trip_counts
0,2112 W Peterson Ave,2112 W Peterson Ave,"(41.991178, -87.683593)","(41.991178, -87.683593)",Female,1.033333,1
1,2112 W Peterson Ave,2112 W Peterson Ave,"(41.991178, -87.683593)","(41.991178, -87.683593)",Male,19.833333,1
2,2112 W Peterson Ave,Broadway & Argyle St,"(41.991178, -87.683593)","(41.973815, -87.65966)",Male,15.950000,1
3,2112 W Peterson Ave,Broadway & Granville Ave,"(41.991178, -87.683593)","(41.9947796884, -87.6602845349)",Male,8.050000,1
4,2112 W Peterson Ave,Broadway & Ridge Ave,"(41.991178, -87.683593)","(41.9840446107, -87.6602738295)",Male,20.066667,3

In [24]:
# Create Database Connection
# ----------------------------------
# Establish Connection
engine = create_engine("sqlite:///riders.sqlite")
conn = engine.connect()

In [25]:
df_merge.to_sql('riders', con=engine, if_exists='replace')
engine.execute("SELECT * FROM riders").fetchall()

[(0, '2112 W Peterson Ave', '2112 W Peterson Ave', '(41.991178, -87.683593)', '(41.991178, -87.683593)', 'Female', 1.0333333333333334, 1),
 (1, '2112 W Peterson Ave', '2112 W Peterson Ave', '(41.991178, -87.683593)', '(41.991178, -87.683593)', 'Male', 19.833333333333332, 1),
 (2, '2112 W Peterson Ave', 'Broadway & Argyle St', '(41.991178, -87.683593)', '(41.973815, -87.65966)', 'Male', 15.95, 1),
 (3, '2112 W Peterson Ave', 'Broadway & Granville Ave', '(41.991178, -87.683593)', '(41.9947796884, -87.6602845349)', 'Male', 8.05, 1),
 (4, '2112 W Peterson Ave', 'Broadway & Ridge Ave', '(41.991178, -87.683593)', '(41.9840446107, -87.6602738295)', 'Male', 20.066666666666666, 3),
 (5, '2112 W Peterson Ave', 'Broadway & Sheridan Rd', '(41.991178, -87.683593)', '(41.952833, -87.649993)', 'Male', 29.566666666666666, 1),
 (6, '2112 W Peterson Ave', 'Broadway & Thorndale Ave', '(41.991178, -87.683593)', '(41.98974251144, -87.6601406209)', 'Male', 7.216666666666667, 10),
 (7, '2112 W Peterson Ave', 'Budlong Woods Library', '(41.991178, -87.683593)', '(41.98366470886, -87.6964225611)', 'Female', 33.21666666666667, 1),
 (8, '2112 W Peterson Ave', 'California Ave & Cortez St', '(41.991178, -87.683593)', '(41.900363, -87.696704)', 'Male', 40.583333333333336, 6),
 (9, '2112 W Peterson Ave', 'Campbell Ave & Montrose Ave', '(41.991178, -87.683593)', '(41.96152593287, -87.6911650414)', 'Male', 18.45, 1),
 (10, '2112 W Peterson Ave', 'Clarendon Ave & Gordon Ter', '(41.991178, -87.683593)', '(41.957879, -87.649519)', 'Male', 23.983333333333334, 1),
 (11, '2112 W Peterson Ave', 'Clarendon Ave & Junior Ter', '(41.991178, -87.683593)', '(41.961004, -87.649603)', 'Male', 24.016666666666666, 1),
 (12, '2112 W Peterson Ave', 'Clark St & Berwyn Ave', '(41.991178, -87.683593)', '(41.9779966544, -87.6680471047)', 'Male', 13.25, 4),
 (13, '2112 W Peterson Ave', 'Clark St & Bryn Mawr Ave', '(41.991178, -87.683593)', '(41.983593, -87.669154)', 'Male', 9.683333333333334, 1),
 (14, '2112 W Peterson Ave', 'Clark St & Elmdale Ave', '(41.991178, -87.683593)', '(41.99051755556753, -87.66983360052109)', 'Male', 6.933333333333334, 1),
 (15, '2112 W Peterson Ave', 'Clark St & Jarvis Ave', '(41.991178, -87.683593)', '(42.015963, -87.675005)', 'Male', 14.05, 1),
 (16, '2112 W Peterson Ave', 'Clark St & Leland Ave', '(41.991178, -87.683593)', '(41.967096, -87.667429)', 'Female', 18.683333333333334, 1),
 (17, '2112 W Peterson Ave', 'Clark St & Lunt Ave', '(41.991178, -87.683593)', '(42.009074, -87.67419)', 'Male', 14.5, 1),
 (18, '2112 W Peterson Ave', 'Clark St & Schreiber Ave', '(41.991178, -87.683593)', '(41.99925182186, -87.6713773393)', 'Female', 14.433333333333334, 2),
 (19, '2112 W Peterson Ave', 'Clark St & Schreiber Ave', '(41.991178, -87.683593)', '(41.99925182186, -87.6713773393)', 'Male', 25.383333333333333, 1),
 (20, '2112 W Peterson Ave', 'Clark St & Winnemac Ave', '(41.991178, -87.683593)', '(41.97334, -87.66778)', 'Male', 15.666666666666666, 1),
 (21, '2112 W Peterson Ave', 'Damen Ave & Chicago Ave', '(41.991178, -87.683593)', '(41.895769, -87.67722)', 'Male', 45.0, 1),
 (22, '2112 W Peterson Ave', 'Damen Ave & Cortland St', '(41.991178, -87.683593)', '(41.915983, -87.677335)', 'Male', 37.8, 1),
 (23, '2112 W Peterson Ave', 'Damen Ave & Pierce Ave', '(41.991178, -87.683593)', '(41.9093960065, -87.6776919292)', 'Male', 34.43333333333333, 1),
 (24, '2112 W Peterson Ave', 'Damen Ave & Sunnyside Ave', '(41.991178, -87.683593)', '(41.96325, -87.679258)', 'Female', 26.15, 1),
 (25, '2112 W Peterson Ave', 'Hoyne Ave & Balmoral Ave', '(41.991178, -87.683593)', '(41.979851, -87.681932)', 'Male', 15.933333333333334, 1),
 (26, '2112 W Peterson Ave', 'Leavitt St & Armitage Ave', '(41.991178, -87.683593)', '(41.917805, -87.682437)', 'Male', 34.11666666666667, 1),
 (27, '2112 W Peterson Ave', 'Leavitt St & Chicago Ave', '(41.991178, -87.683593)', '(41.895501, -87.682017)', 'Male', 42.61666666666667, 1),
 (28, '2112 W Peterson Ave', 'Lincoln Ave & Belle Plaine Ave', '(41.991178, -87.683593)', '(41.95602, -87.680293)', 'Male', 18.116666666666667, 2),
 (29, '2112 W Peterson Ave', 'Lincoln Ave & Sunnyside Ave', '(41.991178, -87.683593)', '(41.963004, -87.684781)', 'Female', 15.933333333333334, 1),
 (30, '2112 W Peterson Ave', 'Lincoln Ave & Sunnyside Ave', '(41.991178, -87.683593)', '(41.963004, -87.684781)', 'Male', 18.783333333333335, 1),
 (31, '2112 W Peterson Ave', 'Logan Blvd & Elston Ave', '(41.991178, -87.683593)', '(41.929465, -87.684158)', 'Male', 33.983333333333334, 1),
 (32, '2112 W Peterson Ave', 'Maplewood Ave & Peterson Ave', '(41.991178, -87.683593)', '(41.99023602867, -87.6933696402)', 'Female', 6.083333333333333, 2),
 (33, '2112 W Peterson Ave', 'Maplewood Ave & Peterson Ave', '(41.991178, -87.683593)', '(41.99023602867, -87.6933696402)', 'Male', 5.083333333333333, 1),
 (34, '2112 W Peterson Ave', 'Marine Dr & Ainslie St', '(41.991178, -87.683593)', '(41.9716, -87.650154)', 'Female', 16.283333333333335, 2),
 (35, '2112 W Peterson Ave', 'Paulina St & Howard St', '(41.991178, -87.683593)', '(42.019159, -87.673573)', 'Male', 19.85, 2),
 (36, '2112 W Peterson Ave', 'Ravenswood Ave & Irving Park Rd', '(41.991178, -87.683593)', '(41.95469, -87.67393)', 'Male', 20.233333333333334, 1),
 (37, '2112 W Peterson Ave', 'Ravenswood Ave & Lawrence Ave', '(41.991178, -87.683593)', '(41.96909, -87.674237)', 'Male', 10.7, 2),
 (38, '2112 W Peterson Ave', 'Sheridan Rd & Greenleaf Ave', '(41.991178, -87.683593)', '(42.01058656284, -87.6624120948)', 'Male', 15.716666666666667, 1),
 (39, '2112 W Peterson Ave', 'Warren Park East', '(41.991178, -87.683593)', '(42.00454962194, -87.6806661451)', 'Female', 17.15, 9),
 (40, '2112 W Peterson Ave', 'Warren Park West', '(41.991178, -87.683593)', '(42.001785, -87.688829)', 'Female', 8.8, 1),
 (41, '2112 W Peterson Ave', 'Warren Park West', '(41.991178, -87.683593)', '(42.001785, -87.688829)', 'Male', 12.666666666666666, 1),
 (42, '2112 W Peterson Ave', 'Western Ave & Granville Ave', '(41.991178, -87.683593)', '(41.99416136902, -87.689438282)', 'Male', 11.3, 4),
 (43, '2112 W Peterson Ave', 'Western Ave & Lunt Ave', '(41.991178, -87.683593)', '(42.0085943972, -87.6904922389)', 'Male', 10.7, 1),
 (44, '2112 W Peterson Ave', 'Winthrop Ave & Lawrence Ave', '(41.991178, -87.683593)', '(41.968812, -87.657659)', 'Male', 20.716666666666665, 2),
 (45, '2112 W Peterson Ave', 'Wolcott (Ravenswood) Ave & Montrose Ave', '(41.991178, -87.683593)', '(41.961406, -87.676169)', 'Male', 21.4, 1),
 (46, '63rd St Beach', '63rd St Beach', '(41.78101637196, -87.5761197602)', '(41.78101637196, -87.5761197602)', 'Female', 25.066666666666666, 2),
 (47, '63rd St Beach', '63rd St Beach', '(41.78101637196, -87.5761197602)', '(41.78101637196, -87.5761197602)', 'Male', 35.05, 6),
 (48, '63rd St Beach', 'Blackstone Ave & Hyde Park Blvd', '(41.78101637196, -87.5761197602)', '(41.802562, -87.590368)', 'Female', 13.733333333333333, 1),
 (49, '63rd St Beach', 'Burnham Harbor', '(41.78101637196, -87.5761197602)', '(41.856268, -87.613348)', 'Female', 35.61666666666667, 2),
 (50, '63rd St Beach', 'Burnham Harbor', '(41.78101637196, -87.5761197602)', '(41.856268, -87.613348)', 'Male', 38.6, 9),
 (51, '63rd St Beach', 'Cornell Ave & Hyde Park Blvd', '(41.78101637196, -87.5761197602)', '(41.802406, -87.586924)', 'Male', 15.6, 12),
 (52, '63rd St Beach', 'Cottage Grove Ave & 51st St', '(41.78101637196, -87.5761197602)', '(41.803038, -87.606615)', 'Male', 23.883333333333333, 1),
 (53, '63rd St Beach', 'Cottage Grove Ave & 63rd St', '(41.78101637196, -87.5761197602)', '(41.78059901484, -87.606112388)', 'Male', 8.366666666666667, 2),
 (54, '63rd St Beach', 'Dorchester Ave & 49th St', '(41.78101637196, -87.5761197602)', '(41.805772, -87.592464)', 'Male', 20.35, 1),
 (55, '63rd St Beach', 'DuSable Museum', '(41.78101637196, -87.5761197602)', '(41.79156801058, -87.6078521774)', 'Male', 16.666666666666668, 1),
 (56, '63rd St Beach', 'Ellis Ave & 53rd St', '(41.78101637196, -87.5761197602)', '(41.79933626261, -87.6009581145)', 'Female', 25.1, 1),
 (57, '63rd St Beach', 'Ellis Ave & 53rd St', '(41.78101637196, -87.5761197602)', '(41.79933626261, -87.6009581145)', 'Male', 25.016666666666666, 1),
 (58, '63rd St Beach', 'Ellis Ave & 58th St', '(41.78101637196, -87.5761197602)', '(41.788746, -87.601334)', 'Female', 21.1, 1),
 (59, '63rd St Beach', 'Ellis Ave & 60th St', '(41.78101637196, -87.5761197602)', '(41.78509714636, -87.6010727606)', 'Male', 10.5, 1),
 (60, '63rd St Beach', 'Fort Dearborn Dr & 31st St', '(41.78101637196, -87.5761197602)', '(41.838556, -87.608218)', 'Female', 35.5, 2),
 (61, '63rd St Beach', 'Fort Dearborn Dr & 31st St', '(41.78101637196, -87.5761197602)', '(41.838556, -87.608218)', 'Male', 31.583333333333332, 6),
 (62, '63rd St Beach', 'Harper Ave & 59th St', '(41.78101637196, -87.5761197602)', '(41.78794281287, -87.5883151702)', 'Female', 24.8, 1),
 (63, '63rd St Beach', 'Harper Ave & 59th St', '(41.78101637196, -87.5761197602)', '(41.78794281287, -87.5883151702)', 'Male', 20.6, 36),
 (64, '63rd St Beach', 'Indiana Ave & Roosevelt Rd', '(41.78101637196, -87.5761197602)', '(41.867888, -87.623041)', 'Male', 42.68333333333333, 1),
 (65, '63rd St Beach', 'Jeffery Blvd & 67th St', '(41.78101637196, -87.5761197602)', '(41.77351755125, -87.5771428255)', 'Female', 25.983333333333334, 1),
 (66, '63rd St Beach', 'Kimbark Ave & 53rd St', '(41.78101637196, -87.5761197602)', '(41.799568, -87.594747)', 'Male', 18.616666666666667, 2),
 (67, '63rd St Beach', 'Lake Park Ave & 35th St', '(41.78101637196, -87.5761197602)', '(41.83127423549, -87.6087991946)', 'Male', 31.583333333333332, 2),
 (68, '63rd St Beach', 'Lake Park Ave & 47th St', '(41.78101637196, -87.5761197602)', '(41.809443, -87.591875)', 'Female', 19.283333333333335, 2),
 (69, '63rd St Beach', 'Lake Park Ave & 47th St', '(41.78101637196, -87.5761197602)', '(41.809443, -87.591875)', 'Male', 28.216666666666665, 1),
 (70, '63rd St Beach', 'Lake Park Ave & 53rd St', '(41.78101637196, -87.5761197602)', '(41.79949429373, -87.5864498959)', 'Female', 12.783333333333333, 1),
 (71, '63rd St Beach', 'Lake Park Ave & 53rd St', '(41.78101637196, -87.5761197602)', '(41.79949429373, -87.5864498959)', 'Male', 21.733333333333334, 6),
 (72, '63rd St Beach', 'Lake Park Ave & 56th St', '(41.78101637196, -87.5761197602)', '(41.793242, -87.587782)', 'Male', 12.216666666666667, 2),
 (73, '63rd St Beach', 'Lake Shore Dr & Monroe St', '(41.78101637196, -87.5761197602)', '(41.880958, -87.616743)', 'Female', 62.71666666666667, 1),
 (74, '63rd St Beach', 'MLK Jr Dr & 29th St', '(41.78101637196, -87.5761197602)', '(41.842052, -87.617)', 'Male', 34.983333333333334, 1),
 (75, '63rd St Beach', 'Museum of Science and Industry', '(41.78101637196, -87.5761197602)', '(41.79172820953, -87.583945009)', 'Male', 15.033333333333333, 13),
 (76, '63rd St Beach', 'Shedd Aquarium', '(41.78101637196, -87.5761197602)', '(41.86722595682, -87.6153553902)', 'Male', 32.333333333333336, 1),
 (77, '63rd St Beach', 'Shore Dr & 55th St', '(41.78101637196, -87.5761197602)', '(41.795212, -87.580715)', 'Female', 10.466666666666667, 4),
 (78, '63rd St Beach', 'Shore Dr & 55th St', '(41.78101637196, -87.5761197602)', '(41.795212, -87.580715)', 'Male', 18.333333333333332, 11),
 (79, '63rd St Beach', 'South Shore Dr & 67th St', '(41.78101637196, -87.5761197602)', '(41.773643, -87.567514)', 'Male', 15.8, 11),
 (80, '63rd St Beach', 'South Shore Dr & 71st St', '(41.78101637196, -87.5761197602)', '(41.7664094567, -87.5656875719)', 'Male', 20.366666666666667, 4),
 (81, '63rd St Beach', 'Stony Island Ave & 75th St', '(41.78101637196, -87.5761197602)', '(41.7586696704, -87.586882871)', 'Male', 17.6, 2),
 (82, '63rd St Beach', 'University Ave & 57th St', '(41.78101637196, -87.5761197602)', '(41.791478, -87.599861)', 'Female', 14.866666666666667, 2),
 (83, '63rd St Beach', 'Wabash Ave & 9th St', '(41.78101637196, -87.5761197602)', '(41.870769, -87.625734)', 'Male', 57.166666666666664, 1),
 (84, '63rd St Beach', 'Woodlawn Ave & 55th St', '(41.78101637196, -87.5761197602)', '(41.795264, -87.596471)', 'Male', 44.0, 1),
 (85, '63rd St Beach', 'Woodlawn Ave & 75th St', '(41.78101637196, -87.5761197602)', '(41.75916, -87.595751)', 'Male', 18.883333333333333, 1),
 (86, '900 W Harrison St', '900 W Harrison St', '(41.874754, -87.649807)', '(41.874754, -87.649807)', 'Female', 40.25, 4),
 (87, '900 W Harrison St', '900 W Harrison St', '(41.874754, -87.649807)', '(41.874754, -87.649807)', 'Male', 6.716666666666667, 9),
 (88, '900 W Harrison St', 'Aberdeen St & Jackson Blvd', '(41.874754, -87.649807)', '(41.87772613, -87.65478743)', 'Female', 4.083333333333333, 12),
 (89, '900 W Harrison St', 'Aberdeen St & Jackson Blvd', '(41.874754, -87.649807)', '(41.87772613, -87.65478743)', 'Male', 5.316666666666666, 22),
 (90, '900 W Harrison St', 'Aberdeen St & Monroe St', '(41.874754, -87.649807)', '(41.880419, -87.655519)', 'Male', 9.25, 3),
 (91, '900 W Harrison St', 'Aberdeen St & Randolph St', '(41.874754, -87.649807)', '(41.884114, -87.654264)', 'Female', 6.95, 8),
 (92, '900 W Harrison St', 'Aberdeen St & Randolph St', '(41.874754, -87.649807)', '(41.884114, -87.654264)', 'Male', 9.55, 3),
 (93, '900 W Harrison St', 'Ada St & Washington Blvd', '(41.874754, -87.649807)', '(41.88283, -87.661206)', 'Female', 8.55, 11),
 (94, '900 W Harrison St', 'Ada St & Washington Blvd', '(41.874754, -87.649807)', '(41.88283, -87.661206)', 'Male', 9.216666666666667, 2),
 (95, '900 W Harrison St', 'Adler Planetarium', '(41.874754, -87.649807)', '(41.866095, -87.607267)', 'Male', 21.6, 6),
 (96, '900 W Harrison St', 'Artesian Ave & Hubbard St', '(41.874754, -87.649807)', '(41.88949181977, -87.6882193648)', 'Male', 18.016666666666666, 1),
 (97, '900 W Harrison St', 'Ashland Ave & 13th St', '(41.874754, -87.649807)', '(41.865234, -87.666507)', 'Male', 12.166666666666666, 4),
 (98, '900 W Harrison St', 'Ashland Ave & 21st St', '(41.874754, -87.649807)', '(41.85381, -87.665897)', 'Female', 18.216666666666665, 1),
 (99, '900 W Harrison St', 'Ashland Ave & 21st St', '(41.874754, -87.649807)', '(41.85381, -87.665897)', 'Male', 14.8, 3),
 (100, '900 W Harrison St', 'Ashland Ave & Blackhawk St', '(41.874754, -87.649807)', '(41.907066, -87.667252)', 'Female', 26.2, 1),
 (101, '900 W Harrison St', 'Ashland Ave & Division St', '(41.874754, -87.649807)', '(41.90345, -87.667747)', 'Female', 21.2, 1),
 (102, '900 W Harrison St', 'Ashland Ave & Division St', '(41.874754, -87.649807)', '(41.90345, -87.667747)', 'Male', 18.45, 1),
 (103, '900 W Harrison St', 'Bissell St & Armitage Ave', '(41.874754, -87.649807)', '(41.91844, -87.65222)', 'Male', 28.8, 1),
 (104, '900 W Harrison St', 'Blue Island Ave & 18th St', '(41.874754, -87.649807)', '(41.857556, -87.661535)', 'Female', 13.166666666666666, 9),
 (105, '900 W Harrison St', 'Blue Island Ave & 18th St', '(41.874754, -87.649807)', '(41.857556, -87.661535)', 'Male', 9.8, 18),
 (106, '900 W Harrison St', 'Broadway & Barry Ave', '(41.874754, -87.649807)', '(41.937725, -87.644095)', 'Female', 33.516666666666666, 1),
 (107, '900 W Harrison St', 'Broadway & Sheridan Rd', '(41.874754, -87.649807)', '(41.952833, -87.649993)', 'Male', 33.95, 1),
 (108, '900 W Harrison St', 'Buckingham Fountain', '(41.874754, -87.649807)', '(41.87651122881695, -87.62054800987242)', 'Female', 13.0, 1),
 (109, '900 W Harrison St', 'Buckingham Fountain', '(41.874754, -87.649807)', '(41.87651122881695, -87.62054800987242)', 'Male', 14.433333333333334, 2),
 (110, '900 W Harrison St', 'Burling St (Halsted) & Diversey Pkwy (Temp)', '(41.874754, -87.649807)', '(41.93314, -87.64776)', 'Female', 28.6, 1),
 (111, '900 W Harrison St', 'Burling St (Halsted) & Diversey Pkwy (Temp)', '(41.874754, -87.649807)', '(41.93314, -87.64776)', 'Male', 28.416666666666668, 2),
 (112, '900 W Harrison St', 'California Ave & Milwaukee Ave', '(41.874754, -87.649807)', '(41.922695, -87.697153)', 'Male', 37.85, 1),
 (113, '900 W Harrison St', 'Calumet Ave & 18th St', '(41.874754, -87.649807)', '(41.857611, -87.619407)', 'Female', 22.083333333333332, 1),
 (114, '900 W Harrison St', 'Calumet Ave & 18th St', '(41.874754, -87.649807)', '(41.857611, -87.619407)', 'Male', 16.733333333333334, 2),
 (115, '900 W Harrison St', 'Calumet Ave & 21st St', '(41.874754, -87.649807)', '(41.85418424947, -87.6191537415)', 'Female', 19.583333333333332, 1),
 (116, '900 W Harrison St', 'Calumet Ave & 21st St', '(41.874754, -87.649807)', '(41.85418424947, -87.6191537415)', 'Male', 18.333333333333332, 1),
 (117, '900 W Harrison St', 'Calumet Ave & 33rd St', '(41.874754, -87.649807)', '(41.8349, -87.61793)', 'Male', 29.733333333333334, 1),
 (118, '900 W Harrison St', 'Canal St & Adams St', '(41.874754, -87.649807)', '(41.879255, -87.639904)', 'Female', 8.483333333333333, 3),
 (119, '900 W Harrison St', 'Canal St & Adams St', '(41.874754, -87.649807)', '(41.879255, -87.639904)', 'Male', 7.166666666666667, 4),
 (120, '900 W Harrison St', 'Canal St & Harrison St', '(41.874754, -87.649807)', '(41.874255, -87.639573)', 'Female', 16.516666666666666, 1),
 (121, '900 W Harrison St', 'Canal St & Harrison St', '(41.874754, -87.649807)', '(41.874255, -87.639573)', 'Male', 8.733333333333333, 4),
 (122, '900 W Harrison St', 'Canal St & Jackson Blvd', '(41.874754, -87.649807)', '(41.877245, -87.639366)', 'Male', 6.783333333333333, 1),
 (123, '900 W Harrison St', 'Canal St & Madison St', '(41.874754, -87.649807)', '(41.882091, -87.639833)', 'Female', 12.716666666666667, 2),
 (124, '900 W Harrison St', 'Canal St & Monroe St', '(41.874754, -87.649807)', '(41.88169, -87.63953)', 'Male', 11.416666666666666, 2),
 (125, '900 W Harrison St', 'Canal St & Taylor St', '(41.874754, -87.649807)', '(41.870257, -87.639474)', 'Female', 7.6, 2),
 (126, '900 W Harrison St', 'Canal St & Taylor St', '(41.874754, -87.649807)', '(41.870257, -87.639474)', 'Male', 6.916666666666667, 17),
 (127, '900 W Harrison St', 'Cityfront Plaza Dr & Pioneer Ct', '(41.874754, -87.649807)', '(41.890573, -87.622072)', 'Male', 35.35, 1),
 (128, '900 W Harrison St', 'Clark St & 9th St (AMLI)', '(41.874754, -87.649807)', '(41.870816, -87.631246)', 'Male', 9.616666666666667, 4),
 (129, '900 W Harrison St', 'Clark St & Elm St', '(41.874754, -87.649807)', '(41.902973, -87.63128)', 'Female', 24.116666666666667, 1),
 (130, '900 W Harrison St', 'Clark St & Grace St', '(41.874754, -87.649807)', '(41.95078, -87.659172)', 'Male', 32.55, 1),
 (131, '900 W Harrison St', 'Clark St & Ida B Wells Dr', '(41.874754, -87.649807)', '(41.8759326655, -87.6305845355)', 'Male', 9.216666666666667, 2),
 (132, '900 W Harrison St', 'Clark St & Lake St', '(41.874754, -87.649807)', '(41.88602082773, -87.6308760584)', 'Male', 13.266666666666667, 1),
 (133, '900 W Harrison St', 'Clark St & Randolph St', '(41.874754, -87.649807)', '(41.884576228, -87.63188991)', 'Female', 18.233333333333334, 1),
 (134, '900 W Harrison St', 'Clinton St & 18th St', '(41.874754, -87.649807)', '(41.85795, -87.640826)', 'Male', 12.3, 2),
 (135, '900 W Harrison St', 'Clinton St & Jackson Blvd', '(41.874754, -87.649807)', '(41.87811603010527, -87.63983845710754)', 'Female', 5.516666666666667, 2),
 (136, '900 W Harrison St', 'Clinton St & Jackson Blvd', '(41.874754, -87.649807)', '(41.87811603010527, -87.63983845710754)', 'Male', 5.283333333333333, 66),
 (137, '900 W Harrison St', 'Clinton St & Lake St', '(41.874754, -87.649807)', '(41.885637, -87.641823)', 'Male', 8.15, 2),
 (138, '900 W Harrison St', 'Clinton St & Madison St', '(41.874754, -87.649807)', '(41.882242, -87.641066)', 'Female', 8.966666666666667, 8),
 (139, '900 W Harrison St', 'Clinton St & Madison St', '(41.874754, -87.649807)', '(41.882242, -87.641066)', 'Male', 9.483333333333333, 34),
 (140, '900 W Harrison St', 'Clinton St & Roosevelt Rd', '(41.874754, -87.649807)', '(41.8671177825, -87.6410879593)', 'Male', 8.116666666666667, 3),
 (141, '900 W Harrison St', 'Clinton St & Tilden St', '(41.874754, -87.649807)', '(41.875885, -87.640795)', 'Male', 8.6, 1),

In [34]:
df_from = df_ridercount.groupby(['Station_Name_x', 'Station_Name_y','gender']).sum().reset_index()
df_from.head()

NameError: name 'df_ridercount' is not defined

In [26]:
# Capture all data from the hist_trips table inside hist_trips.sqlite
trips_tbl = pd.read_sql("SELECT * FROM riders", con=engine)
trips_tbl

,index,Station_Name_x,Station_Name_y,Location_x,Location_y,gender,Avg_duration,Trip_counts
0,0,2112 W Peterson Ave,2112 W Peterson Ave,"(41.991178, -87.683593)","(41.991178, -87.683593)",Female,1.033333,1
1,1,2112 W Peterson Ave,2112 W Peterson Ave,"(41.991178, -87.683593)","(41.991178, -87.683593)",Male,19.833333,1
2,2,2112 W Peterson Ave,Broadway & Argyle St,"(41.991178, -87.683593)","(41.973815, -87.65966)",Male,15.950000,1
3,3,2112 W Peterson Ave,Broadway & Granville Ave,"(41.991178, -87.683593)","(41.9947796884, -87.6602845349)",Male,8.050000,1
4,4,2112 W Peterson Ave,Broadway & Ridge Ave,"(41.991178, -87.683593)","(41.9840446107, -87.6602738295)",Male,20.066667,3
5,5,2112 W Peterson Ave,Broadway & Sheridan Rd,"(41.991178, -87.683593)","(41.952833, -87.649993)",Male,29.566667,1
6,6,2112 W Peterson Ave,Broadway & Thorndale Ave,"(41.991178, -87.683593)","(41.98974251144, -87.6601406209)",Male,7.216667,10
7,7,2112 W Peterson Ave,Budlong Woods Library,"(41.991178, -87.683593)","(41.98366470886, -87.6964225611)",Female,33.216667,1
8,8,2112 W Peterson Ave,California Ave & Cortez St,"(41.991178, -87.683593)","(41.900363, -87.696704)",Male,40.583333,6
9,9,2112 W Peterson Ave,Campbell Ave & Montrose Ave,"(41.991178, -87.683593)","(41.96152593287, -87.6911650414)",Male,18.450000,1
10,10,2112 W Peterson Ave,Clarendon Ave & Gordon Ter,"(41.991178, -87.683593)","(41.957879, -87.649519)",Male,23.983333,1
11,11,2112 W Peterson Ave,Clarendon Ave & Junior Ter,"(41.991178, -87.683593)","(41.961004, -87.649603)",Male,24.016667,1
12,12,2112 W Peterson Ave,Clark St & Berwyn Ave,"(41.991178, -87.683593)","(41.9779966544, -87.6680471047)",Male,13.250000,4
13,13,2112 W Peterson Ave,Clark St & Bryn Mawr Ave,"(41.991178, -87.683593)","(41.983593, -87.669154)",Male,9.683333,1
14,14,2112 W Peterson Ave,Clark St & Elmdale Ave,"(41.991178, -87.683593)","(41.99051755556753, -87.66983360052109)",Male,6.933333,1
15,15,2112 W Peterson Ave,Clark St & Jarvis Ave,"(41.991178, -87.683593)","(42.015963, -87.675005)",Male,14.050000,1
16,16,2112 W Peterson Ave,Clark St & Leland Ave,"(41.991178, -87.683593)","(41.967096, -87.667429)",Female,18.683333,1
17,17,2112 W Peterson Ave,Clark St & Lunt Ave,"(41.991178, -87.683593)","(42.009074, -87.67419)",Male,14.500000,1
18,18,2112 W Peterson Ave,Clark St & Schreiber Ave,"(41.991178, -87.683593)","(41.99925182186, -87.6713773393)",Female,14.433333,2
19,19,2112 W Peterson Ave,Clark St & Schreiber Ave,"(41.991178, -87.683593)","(41.99925182186, -87.6713773393)",Male,25.383333,1
20,20,2112 W Peterson Ave,Clark St & Winnemac Ave,"(41.991178, -87.683593)","(41.97334, -87.66778)",Male,15.666667,1
21,21,2112 W Peterson Ave,Damen Ave & Chicago Ave,"(41.991178, -87.683593)","(41.895769, -87.67722)",Male,45.000000,1
22,22,2112 W Peterson Ave,Damen Ave & Cortland St,"(41.991178, -87.683593)","(41.915983, -87.677335)",Male,37.800000,1
23,23,2112 W Peterson Ave,Damen Ave & Pierce Ave,"(41.991178, -87.683593)","(41.9093960065, -87.6776919292)",Male,34.433333,1
24,24,2112 W Peterson Ave,Damen Ave & Sunnyside Ave,"(41.991178, -87.683593)","(41.96325, -87.679258)",Female,26.150000,1
25,25,2112 W Peterson Ave,Hoyne Ave & Balmoral Ave,"(41.991178, -87.683593)","(41.979851, -87.681932)",Male,15.933333,1
26,26,2112 W Peterson Ave,Leavitt St & Armitage Ave,"(41.991178, -87.683593)","(41.917805, -87.682437)",Male,34.116667,1
27,27,2112 W Peterson Ave,Leavitt St & Chicago Ave,"(41.991178, -87.683593)","(41.895501, -87.682017)",Male,42.616667,1
28,28,2112 W Peterson Ave,Lincoln Ave & Belle Plaine Ave,"(41.991178, -87.683593)","(41.95602, -87.680293)",Male,18.116667,2
29,29,2112 W Peterson Ave,Lincoln Ave & Sunnyside Ave,"(41.991178, -87.683593)","(41.963004, -87.684781)",Female,15.933333,1
...,...,...,...,...,...,...,...,...
109285,109285,Woodlawn Ave & Lake Park Ave,Lake Park Ave & 47th St,"(41.81409271048, -87.5970051479)","(41.809443, -87.591875)",Male,3.616667,12
109286,109286,Woodlawn Ave & Lake Park Ave,Lake Park Ave & 53rd St,"(41.81409271048, -87.5970051479)","(41.79949429373, -87.5864498959)",Female,10.750000,2
109287,109287,Woodlawn Ave & Lake Park Ave,Lake Park Ave & 53rd St,"(41.81409271048, -87.5970051479)","(41.79949429373, -87.5864498959)",Male,14.050000,2
109288,109288,Woodlawn Ave & Lake Park Ave,MLK Jr Dr & 47th St,"(41.81409271048, -87.5970051479)","(41.809851, -87.616279)",Female,10.650000,1
109289,109289,Woodlawn Ave & Lake Park Ave,MLK Jr Dr & Pershing Rd,"(41.81409271048, -87.5970051479)","(41.8246, -87.61678)",Male,14.800000,1
109290,109290,Woodlawn Ave & Lake Park Ave,Museum of Science and Industry,"(41.81409271048, -87.5970051479)","(41.79172820953, -87.583945009)",Male,29.666667,1
109291,109291,Woodlawn Ave & Lake Park Ave,Normal Ave & Archer Ave,"(41.81409271048, -87.5970051479)","(41.849527, -87.640591)",Male,27.433333,1
109292,109292,Woodlawn Ave & Lake Park Ave,Prairie Ave & 43rd St,"(41.81409271048, -87.5970051479)","(41.81665889302, -87.6194124619)",Male,8.616667,13
109293,109293,Woodlawn Ave & Lake Park Ave,Shedd Aquarium,"(41.81409271048, -87.5970051479)","(41.86722595682, -87.6153553902)",Female,38.216667,1
109294,109294,Woodlawn Ave & Lake Park Ave,South Shore Dr & 67th St,"(41.81409271048, -87.5970051479)","(41.773643, -87.567514)",Female,51.383333,1
109295,109295,Woodlawn Ave & Lake Park Ave,State St & 35th St,"(41.81409271048, -87.5970051479)","(41.8309, -87.62803)",Female,16.216667,3
109296,109296,Woodlawn Ave & Lake Park Ave,University Ave & 57th St,"(41.81409271048, -87.5970051479)","(41.791478, -87.599861)",Female,16.083333,2
109297,109297,Woodlawn Ave & Lake Park Ave,University Ave & 57th St,"(41.81409271048, -87.5970051479)","(41.791478, -87.599861)",Male,11.916667,1
109298,109298,Woodlawn Ave & Lake Park Ave,Woodlawn Ave & 55th St,"(41.81409271048, -87.5970051479)","(41.795264, -87.596471)",Male,9.283333,23
109299,109299,Woodlawn Ave & Lake Park Ave,Woodlawn Ave & Lake Park Ave,"(41.81409271048, -87.5970051479)","(41.81409271048, -87.5970051479)",Female,20.250000,7
109300,109300,Woodlawn Ave & Lake Park Ave,Woodlawn Ave & Lake Park Ave,"(41.81409271048, -87.5970051479)","(41.81409271048, -87.5970051479)",Male,33.116667,8
109301,109301,Yates Blvd & 75th St,63rd St Beach,"(41.758768, -87.56644)","(41.78101637196, -87.5761197602)",Male,21.983333,1
109302,109302,Yates Blvd & 75th St,Commercial Ave & 83rd St,"(41.758768, -87.56644)","(41.744615, -87.551208)",Male,15.166667,2
109303,109303,Yates Blvd & 75th St,Eggleston Ave & 69th St (*),"(41.758768, -87.56644)","(41.768898, -87.635876)",Male,32.966667,1
109304,109304,Yates Blvd & 75th St,Jeffery Blvd & 67th St,"(41.758768, -87.56644)","(41.77351755125, -87.5771428255)",Male,11.016667,1
109305,109305,Yates Blvd & 75th St,Jeffery Blvd & 71st St,"(41.758768, -87.56644)","(41.76663823695, -87.5764501141)",Male,6.716667,7
109306,109306,Yates Blvd & 75th St,Jeffery Blvd & 76th St,"(41.758768, -87.56644)","(41.75712006802, -87.5758393587)",Female,7.600000,1
109307,109307,Yates Blvd & 75th St,Kimbark Ave & 53rd St,"(41.758768, -87.56644)","(41.799568, -87.594747)",Male,33.250000,2
109308,109308,Yates Blvd & 75th St,MLK Jr Dr & 56th St,"(41.758768, -87.56644)","(41.79342945658, -87.6158532619)",Male,28.750000,2
109309,109309,Yates Blvd & 75th St,Princeton Ave & 47th St,"(41.758768, -87.56644)","(41.80931770924, -87.633449288)",Male,44.100000,1
109310,109310,Yates Blvd & 75th St,Rainbow Beach,"(41.758768, -87.56644)","(41.75787144829, -87.54938625)",Male,17.616667,1
109311,109311,Yates Blvd & 75th St,South Shore Dr & 71st St,"(41.758768, -87.56644)","(41.7664094567, -87.5656875719)",Male,11.966667,1
109312,109312,Yates Blvd & 75th St,South Shore Dr & 74th St,"(41.758768, -87.56644)","(41.76218896038, -87.55927465)",Female,4.850000,2
109313,109313,Yates Blvd & 75th St,Stony Island Ave & 71st St,"(41.758768, -87.56644)","(41.7664929373, -87.5864608775)",Male,14.133333,1
109314,109314,Yates Blvd & 75th St,Yates Blvd & 75th St,"(41.758768, -87.56644)","(41.758768, -87.56644)",Male,16.150000,1

In [142]:
df_from = df_from.rename(columns = {'tripduration': 'Trip_counts'})
df_from.head()

        Station Name_x  gender  Trip_counts
0  2112 W Peterson Ave  Female           11
1  2112 W Peterson Ave    Male           32
2        63rd St Beach  Female            8
3        63rd St Beach    Male           46
4    900 W Harrison St  Female          337

In [1]:
df_top10_from = df_from.sort_values('Trip_counts', ascending=False)
df_top10_from_female = df_top10_from.loc[df_top10_from['gender'] == 'Female']
df_top10_from_female = df_top10_from_female.nlargest(10,'Trip_counts')
df_top10_from_female

NameError: name 'df_from' is not defined

In [140]:
df_top10_from = df_from.sort_values('Trip_counts', ascending=False)
df_top10_from_male = df_top10_from.loc[df_top10_from['gender'] == 'Male']
df_top10_from_male = df_top10_from_male.nlargest(10,'Trip_counts')
df_top10_from_male

                   Station Name_x gender  Trip_counts
155           Canal St & Adams St   Male         9742
282  Clinton St & Washington Blvd   Male         9273
274       Clinton St & Madison St   Male         8569
286     Columbus Dr & Randolph St   Male         6489
161         Canal St & Madison St   Male         5803
448       Franklin St & Monroe St   Male         5697
574      Kingsbury St & Kinzie St   Male         5602
310            Daley Center Plaza   Male         5052
589     LaSalle St & Jackson Blvd   Male         4149
736  Michigan Ave & Washington St   Male         4134